kube-burner/kube-burner

- pkg/indexers/elastic.go
> Improve ES ping

- README.md
- cmd/kube-burner.go
- pkg/indexers/elastic.go
- pkg/prometheus/prometheus.go
> Modify quay URL

- README.md
- cmd/kube-burner.go
- examples/cfg.yml
- pkg/burner/burner.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/prometheus/prometheus.go
Add object verification feature. By default, verify that the created objects have been created. In case of verification error, exit with with return code 1 after indexing the metrics (if indexing is enabled). If errorOnVerify is true Exit before indexing metrics.
i.e
verifyObjects and errorOnVerify: false
```
INFO[2020-09-15 13:10:49] Verifying created objects                                                                                                                                                                                           
INFO[2020-09-15 13:10:49] imagestreams found: 12 Expected: 12 …
```
> Verify objects

- .github/workflows/go.yml
- Containerfile
- Makefile
- examples/cfg.yml
- pkg/burner/burner.go
- test/kind.yml
- test/kube-burner.yml
- test/objectTemplates/deployment.yml
> Preliminary e2e CI implementation

- pkg/indexers/elastic.go
> Improve ES health checking

- README.md
- examples/cfg.yml
- pkg/measurements/podLatency.go
- test/kube-burner.yml
> Use only one index for pod latency measurement

- pkg/burner/burner.go
BuildConfig generates a build object, let's add the same wait function for them.
> Buildconfig wait

- README.md
- pkg/burner/burner.go
- pkg/burner/ocp-waiters.go
- pkg/burner/waiters.go
- pkg/config/config.go
- pkg/config/types.go
This PR adds the following:
- DNS1123 validation to namespace and job names. Required to prevent creation errors for namespaces and objects.
- Add wait timeout mechanism. Required to prevent infinite waits.
> Wait timeout

- cmd/kube-burner.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/indexers/elastic.go
> Don't require jobs for indexing and destroy

- .github/workflows/go.yml
- pkg/burner/burner.go
- pkg/burner/namespaces.go
- test/kube-burner.yml
- test/objectTemplates/deployment.yml
With this PR, now objects and namespaces are created in order:
```
INFO[2020-10-03 03:18:55] Creating namespace load-monitoring-35                                                                                                                                                                               
INFO[2020-10-03 03:18:56] Created Deployment eagle-35-1 on load-monitoring-35                                                                                                                                                                 
INFO[2020-10-03 03:18:56] Created Deployment eagle-35-6 on load-monitoring-35                                                                                                                                                                 
INFO[2020-10-03 …
```
> Create objects and namespaces in order

- .github/workflows/release.yml
- .goreleaser.yml
> Include goreleaser action

- README.md
- cmd/kube-burner.go
- examples/cfg.yml
- pkg/burner/burner.go
- pkg/burner/waiters.go
- pkg/config/config.go
- pkg/config/types.go
- test/kube-burner.yml
> Convert some types to time.Duration

- pkg/prometheus/prometheus.go
> Remove __name__ label from metrics

- pkg/burner/waiters.go
There're situations where builds don't have status yet, and when a build has not been created after creating a buildconfig. This PR improves that behavior.
> Improve build wait function

- pkg/burner/burner.go
Before this PR. Jobs with only one object replica/iteration don't meet QPS because kube-burner waited for that object to be created before starting the new iteration.
> Optimize object creation

- .github/workflows/go.yml
- Makefile
- README.md
- pkg/burner/template-utils.go
- pkg/indexers/elastic.go
- pkg/prometheus/prometheus.go
- test/kube-burner.yml
- test/run.sh
> Improve CI testing

- cmd/kube-burner.go
- pkg/burner/burner.go
Better error messages for some errors.
> Improved error messages

- pkg/indexers/factory.go
- pkg/measurements/podLatency.go
- pkg/prometheus/prometheus.go
> Fix usage of interface array

- README.md
- examples/cfg.yml
- pkg/config/types.go
- pkg/indexers/elastic.go
> Remove ES username and password parameters

- pkg/burner/create.go
> Fix job end time

- pkg/burner/job.go
> Unique job names

- test/base.sh
- test/run.sh
> Increase CI verbosity

- pkg/burner/delete.go
- pkg/burner/utils.go
There are situations where listing can fail due to a high load in the API services. These issues are not properly handled, this can cause a panic in the job as shown below:
```
time="2020-10-30 20:39:11" level=info msg="secrets found: 40000 Expected: 40000"
time="2020-10-30 20:39:15" level=error msg="Error verifying object: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (2775296194 vs. 2147483647)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12914af]
goroutine 1 [running]:
github.com/cloud-bulldozer/kube-burner/pkg/burner.(*Executor).Verify(0xc00015c000, 0x1)
/root/kube-burner/pkg/burner/utils.go:72 +0x40f …
```
> Retry list operations

- README.md
- cmd/kube-burner.go
- pkg/burner/metadata.go
- pkg/config/types.go
- pkg/measurements/pod_latency.go
- pkg/prometheus/prometheus.go
> Generate job summary document

- pkg/config/types.go
> Remove deprecated namespaced field

- README.md
- cmd/kube-burner.go
- pkg/indexers/factory.go
- pkg/measurements/factory.go
- pkg/prometheus/prometheus.go
- test/metrics-profile.yaml
Instant query functionality. Useful to index instantaneous metrics such as API version.
> Instant query functionality

- pkg/measurements/pod_latency.go
> Add pod name and namespace to podLatency measurement

- .golangci.yml
> Increase golanci timeout

- pkg/measurements/pod_latency.go
Skip latency reporting from failed/pending pods, to prevent situations were reported latency is zero.
> Fix podLatency for failed pods

- Makefile
- README.md
- cmd/kube-burner.go
- pkg/burner/create.go
- pkg/burner/namespaces.go
- pkg/config/config.go
- pkg/prometheus/prometheus.go
- pkg/util/url_reader.go
Couple of things: 
- Include remote configuration retrival
- Improve authorization error handling
> Include remote configuration retrival

- cmd/kube-burner.go
- pkg/burner/create.go
- pkg/burner/utils.go
Add a couple of template options to improve error handling
> Template options

- pkg/burner/utils.go
Will prevent ugly error messages caused when listing objects with a size higher than `2147483647`. cc: @chaitanyaenr 
```
`level=error msg="Error verifying object: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (2789558005 vs. 2147483647)".
```
> Pagination in object verify

- cmd/kube-burner.go
- docs/ALERTING.md
- docs/INDEXERS.md
- mkdocs.yml
- pkg/alerting/alert_manager.go
- pkg/prometheus/prometheus.go
- pkg/util/url_reader.go
- test/alert-profile.yaml
- test/run.sh
> Alerting feature

- pkg/burner/create.go
Informative message for null QPS and burst parameters
> Null QPS and burst log messages

- pkg/burner/utils.go
> Fix typo in verification log

- pkg/prometheus/prometheus.go
> Use end for instant queries

- cmd/kube-burner.go
Alerting and metrics scrape should use the same end date
> Alerts date

- README.md
- cmd/kube-burner.go
- docs/index.md
- docs/measurements.md
- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/config/validations.go
- pkg/measurements/factory.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
Stablish pod latency thresholds for the different pod conditions and metrics through the option `thresholds` from the podLatency measurement
> Latency thresholds

- pkg/burner/delete.go
- pkg/config/config.go
> Validate namespace name only in creation jobs

- docs/configuration.md
- pkg/burner/job.go
- pkg/burner/utils.go
- pkg/config/types.go
> Rand function

- pkg/alerting/alert_manager.go
- pkg/burner/create.go
- pkg/config/config.go
- pkg/prometheus/prometheus.go
- pkg/util/url_reader.go
> Config retrieval fallback function

- pkg/burner/create.go
> Fix map concurrent access issues present in high QPS benchmarks

- pkg/burner/create.go
- pkg/burner/waiters.go
> Parallel object wait

- .github/workflows/go.yml
- .github/workflows/release.yml
CI will now require an approval to be triggered.
> Protect CI by adding it to and environment

- docs/configuration.md
- pkg/burner/utils.go
Adds:
- add
- multiply
- sequence
custom functions to allow for some better templating in the config files
> Add several custom functions for more dynamic gotemplates

- cmd/kube-burner/kube-burner.go
- go.mod
- go.sum
- pkg/burner/create.go
- pkg/config/config.go
- pkg/util/template.go
- test/base.sh
- test/kube-burner.yml
- vendor/github.com/spf13/cast/.gitignore
- vendor/github.com/spf13/cast/.travis.yml
- vendor/github.com/spf13/cast/LICENSE
- vendor/github.com/spf13/cast/Makefile
- vendor/github.com/spf13/cast/README.md
- vendor/github.com/spf13/cast/cast.go
- vendor/github.com/spf13/cast/caste.go
- vendor/github.com/spf13/cast/go.mod
- vendor/github.com/spf13/cast/go.sum
- vendor/modules.txt
add and multiply functions can now receive any number of arguments.
These functions are now able to receive environment variables as input parameter:
i.e.
```go
{{ range $i, $v := sequence 0 .MY_ENV_VAR }}
{{ $v }}
{{ end }}
```
In addition, namespaces created by kube-burner are also labeled now with `name=<namespaceName>` 
cc: @akrzos
> Template functions improvements

- pkg/burner/namespaces.go
Return err in namespace creation error. Helps to fix linting as well
> Return err in namespace creation error

- .golangci.yml
- docs/measurements.md
- pkg/burner/namespaces.go
- pkg/config/types.go
- pkg/measurements/pprof.go
Add certificate authentication to pprof collection
> Pprof cert auth

- docs/cli.md
- docs/configuration.md
Several improvements for the UUID flat documentation
https://github.com/cloud-bulldozer/kube-burner/issues/78
> Improve UUID documentation

- docs/configuration.md
- mkdocs.yml
Some documentation reorganization.
> Docs reorg

- .goreleaser.yml
Add ppc little endian format to goreleaser
#80
> Add little-endian ppc

- docs/configuration.md
- docs/index.md
- pkg/util/template.go
Template function to generate integer numbers between a given range.
> Random integer generation in templates

- .github/workflows/go.yml
- cmd/kube-burner/kube-burner.go
- docs/cli.md
- docs/configuration.md
- docs/contributing.md
- docs/index.md
- docs/metrics.md
- examples/cfg.yml
- pkg/burner/metadata.go
- pkg/config/types.go
- pkg/indexers/elastic.go
- pkg/indexers/factory.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/tarball.go
Implementation of the metric export/import feature. Metrics tarball can be generated after running a benchmark or from the `index` sub-command.
https://github.com/cloud-bulldozer/kube-burner/issues/87
> Metric exporting & importing

- .github/workflows/go.yml
- pkg/burner/waiters.go
- test/base.sh
- test/kube-burner.yml
- test/run.sh
- test/setup-kind.sh
> Print events on error

- cmd/kube-burner/kube-burner.go
- examples/workloads/cluster-density/cluster-density.yml
- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/job.go
- pkg/config/config.go
- pkg/config/types.go
Simplify and standarize k8s config discovery mechanism
> Config discovery

- .github/workflows/containers.yml
- .github/workflows/go.yml
- Containerfile
- Makefile
Build multiarchitecture binaries and containers from makefile
> Build multiarch binaries and containers from makefile

- cmd/kube-burner/kube-burner.go
- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/namespaces.go
Decreasing default verbosity by moving more verbose messages to DEBUG level
> Decrease default verbosity

- .github/workflows/containers.yml
- Makefile
Automate container manifest creation and refresh
> Automate manifest building

- pkg/config/types.go
> Remove unused types

- docs/measurements.md
- docs/metrics.md
- pkg/measurements/pprof.go
- pkg/measurements/types/types.go
Now certFile and keyFile point to certificate/private key files respectively and cert and key hold the content of them.
cc: @Harshith-umesh
> String based certs for pprof measurement

- Containerfile
Allows copying of pprof folder from the pod onto the machine.
> Install rsync on kube-burner container

- pkg/measurements/pprof.go
> Improve pprof error handling

- .github/workflows/containers.yml
- .goreleaser.yml
- Makefile
> Add s390x arch

- pkg/burner/create.go
- pkg/burner/namespaces.go
- pkg/util/template.go
- pkg/util/url_reader.go
> Logging improvements

- docs/measurements.md
- pkg/measurements/pod_latency.go
Will be helpful to debug this metric.
> Add nodeName to pod latency metrics

- pkg/measurements/pod_latency.go
> nodeName camelcase

- pkg/burner/delete.go
> Check for map lenght rather than nil

- cmd/kube-burner/kube-burner.go
> Return code 1, when command fails

- cmd/kube-burner/kube-burner.go
> Improve version log message

- pkg/indexers/elastic.go
Indexing needs better stats and a higher timeout
> Improve indexing stats and increase timeout

- pkg/indexers/elastic.go
Multiple bulk indexer items OnSuccess callbacks could concurrently
access the indexer stats map.
@jtaleric @whitleykeith
> elastic: protect access to indexer stats map

- examples/workloads/kubelet-density-cni-networkpolicy/kubelet-density-cni-networkpolicy.yml
- examples/workloads/kubelet-density-cni/kubelet-density-cni.yml
Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>
> Fix typo in preLoadImages

- docs/configuration.md
> Fix doc typo

- cmd/kube-burner/kube-burner.go
- docs/configuration.md
- pkg/burner/create.go
- pkg/burner/job.go
- pkg/burner/patch.go
- pkg/config/config.go
- pkg/config/types.go
Adds the option to create not namespaced resources.
- Fixes: https://github.com/cloud-bulldozer/kube-burner/issues/143
>  [WIP] Namespaced resources

- pkg/config/config.go
> Remove Println

- .github/workflows/containers.yml
> Fix containers pipeline

- cmd/kube-burner/kube-burner.go
- docs/alerting.md
- pkg/alerting/alert_manager.go
- pkg/burner/create.go
- pkg/measurements/metrics/metrics.go
- test/alert-profile.yaml
Pass the rendered variable to alert expressions
> Alert duration variable

- .github/workflows/go.yml
- pkg/burner/waiters.go
- pkg/measurements/metrics/metrics.go
- pkg/measurements/pod_latency.go
> Log improvements

- docs/metrics.md
- pkg/burner/namespaces.go
- pkg/prometheus/prometheus.go
- test/alert-profile.yaml
- test/base.sh
- test/kube-burner.yml
- test/metrics-profile.yaml
- test/run.sh
Make the {{.elapsed}} magic variable available to prometheus queries.
> Elapsed magic variable

- .github/workflows/containers.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
> Bump golang version

- pkg/measurements/vmi_latency.go
> Remove duplicated import

- .github/workflows/go.yml
- test/base.sh
- test/run.sh
- test/setup-kind.sh
> Bump k8s version in tests

- pkg/burner/create.go
- pkg/burner/job.go
- pkg/burner/utils.go
- pkg/burner/waiters.go
- pkg/config/types.go
Some code optimizations and house keeping
> Code optimizations

- authors.md
- docs/authors.md
- mkdocs.yml
This section is not updated regularly, better to get rid of it.
> Remove authors section

- pkg/burner/waiters.go
Adding more object types to wait for bound/running
Includes: 
PVC
Statefulsets to have all running pods
Be able to properly wait for creation of multiple objects
> Adding pvc waiter for bound and statefulset replicas running

- .github/workflows/kube-burner.yml
> Add OCP CI concurrency barrier

- .github/workflows/kube-burner.yml
- .golangci.yml
- cmd/kube-burner/ocp.go
- pkg/burner/job.go
- pkg/burner/pre_load.go
- pkg/config/config.go
- pkg/measurements/pod_latency.go
- pkg/measurements/vmi_latency.go
- pkg/workloads/helpers.go
It fails when there're trailing slashes in the es-url. Also adding more debugging log messages in case of error.
> Fix cluster metadata indexing

- .github/workflows/kube-burner.yml
> Update linter version

- .github/workflows/kube-burner.yml
> Fix linter error

- cmd/kube-burner/ocp.go
- docs/ocp.md
The indexing value now is automatically set.
> Remove indexing flag

- .github/workflows/containers.yml
- .github/workflows/kube-burner.yml
- Containerfile
- Makefile
We can leverage the flag --platform to build multiarch containers to simplify the process.
> Improvements on the multi-arch container build pipeline

- Makefile
> Don't push the container image

- cmd/kube-burner/ocp-config/node-density-cni/curl-deployment.yml
- cmd/kube-burner/ocp-config/node-density-cni/node-density-cni.yml
- cmd/kube-burner/ocp-config/node-density-cni/webserver-deployment.yml
- cmd/kube-burner/ocp-config/node-density-cni/webserver-service.yml
- cmd/kube-burner/ocp.go
- docs/ocp.md
- pkg/workloads/node-density-cni.go
- test/run-ocp.sh
Add node-density-cni workload to the OCP wrapper.
cc: @afcollins
> Add node-density-cni

- cmd/kube-burner/ocp.go
- docs/ocp.md
- pkg/workloads/helpers.go
- pkg/workloads/node-density-cni.go
Divide by 2 the number of node-density-cni iterations
cc: @afcollins
> Divide by 2 the number of iterations in node-density-cni

- cmd/kube-burner/ocp-config/node-density-heavy/app-deployment.yml
> Update perfApp location

- pkg/burner/job.go
Fixes: #219
I have to add a test case of running kube-burner without indexing...
> Don't append to prometheus JobList unless prometheus is initialized

- cmd/kube-burner/kube-burner.go
- cmd/kube-burner/ocp-config/cluster-density/cluster-density.yml
- cmd/kube-burner/ocp-config/node-density-cni/alerts.yml
- cmd/kube-burner/ocp-config/node-density-cni/metrics.yml
- cmd/kube-burner/ocp-config/node-density-cni/node-density-cni.yml
- cmd/kube-burner/ocp-config/node-density-heavy/node-density-heavy.yml
- cmd/kube-burner/ocp-config/node-density/node-density.yml
- cmd/kube-burner/ocp.go
- docs/configuration.md
- pkg/alerting/alert_manager.go
- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/job.go
- pkg/burner/namespaces.go
- pkg/burner/patch.go
- pkg/burner/pre_load.go
- pkg/burner/utils.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/measurements/factory.go
- pkg/workloads/helpers.go
- test/run-ocp.sh
Garbage collect created namespaces.
Also unifying up clientSet creation,
> Option to garbage collect created namespaces.

- .github/workflows/kube-burner.yml
- pkg/discovery/discovery.go
- pkg/workloads/helpers.go
> Fix build errors

- .github/workflows/kube-burner.yml
> Checkout code

- test/run-ocp.sh
> Set UUID in test

- cmd/kube-burner/ocp-config/cluster-density/deployment-client.yml
- cmd/kube-burner/ocp-config/cluster-density/service.yml
> Remove https port from service

- pkg/burner/create.go
- test/run-ocp.sh
This change should increase the waiters go routines by 2, it should cut down the duration of this workload's stage.
cc: @afcollins 
> Increase waiters go routines

- cmd/kube-burner/ocp-config/node-density-cni/curl-deployment.yml
- cmd/kube-burner/ocp-config/node-density-cni/webserver-deployment.yml
- cmd/kube-burner/ocp-config/node-density-heavy/app-deployment.yml
- cmd/kube-burner/ocp-config/node-density-heavy/postgres-deployment.yml
- cmd/kube-burner/ocp-config/node-density/pod.yml
- pkg/discovery/discovery.go
- pkg/discovery/types.go
We need to update this expression for the wrapper to be used against managed-clusters
> Fix nodeSelector expression

- cmd/kube-burner/ocp-config/node-density-cni/curl-deployment.yml
- cmd/kube-burner/ocp-config/node-density-cni/webserver-deployment.yml
- cmd/kube-burner/ocp-config/node-density-heavy/app-deployment.yml
- cmd/kube-burner/ocp-config/node-density-heavy/postgres-deployment.yml
- cmd/kube-burner/ocp-config/node-density/pod.yml
> Fix affinity expression

- cmd/kube-burner/ocp-config/cluster-density/cluster-density.yml
- cmd/kube-burner/ocp-config/cluster-density/deployment-client.yml
- cmd/kube-burner/ocp-config/cluster-density/np-allow-from-clients.yml
> Deploy 3 network-policies rather than 4

- cmd/kube-burner/kube-burner.go
- cmd/kube-burner/ocp.go
- docs/alerting.md
- pkg/alerting/alert_manager.go
- pkg/burner/job.go
- pkg/prometheus/prometheus.go
- pkg/workloads/helpers.go
- test/alert-profile.yaml
- test/kube-burner.yml
Adding the alert indexing feature. Alerts are indexed in the index configured by defaultIndex.
NewAlertManager now receives an indexer as parameter, hence the indexer must be created outside of the Run function
> Alert indexing

- pkg/burner/metadata.go
Index kube-burner version information along with workload metadata info
> Index kube-burner version information along with workload metadata info

- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/job.go
When an error happens we shouldn't quit the PollImmediateInfinite loop but keep trying and print the error
- Fixes: #260
> Don't return on error while waiting for stuff removal

- cmd/kube-burner/ocp-config/cluster-density/deployment.yml
- cmd/kube-burner/ocp-config/node-density/node-density.yml
- examples/workloads/api-intensive/templates/deployment.yaml
- examples/workloads/api-intensive/templates/deployment_patch_add_pod_2.yaml
- examples/workloads/cluster-density/templates/deployment.yml
- examples/workloads/kubelet-density/kubelet-density.yml
- pkg/util/metrics/metrics.go
- pkg/util/metrics/utils.go
- pkg/workloads/helpers.go
- test/base.sh
- test/kube-burner.yml
- test/run.sh
> Update prometheus URL conditional

- pkg/alerting/alert_manager.go
- pkg/burner/job.go
- pkg/config/config.go
- pkg/prometheus/prometheus.go
- pkg/util/metrics/utils.go
- pkg/util/template.go
- pkg/workloads/helpers.go
Handle metrics-profile and metrics-endpoint files as templates to add them more flexibility
> Render metrics endpoint and metrics profile cfg

- test/kube-burner.yml
Reduce preLoadPeriod to 5s to save some minutes
> Speed up e2e tests

- cmd/kube-burner/ocp-config/cluster-density-v2/deployment-client.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/deployment-server.yml
- cmd/kube-burner/ocp-config/cluster-density/deployment.yml
- pkg/workloads/helpers.go
Remove unused tolerations from workloads and improve logging when reusing config file
> Remove tolerations

- pkg/burner/create.go
It's useful to provide some information to the user about the progress of the workload
> Print progress when each 1/10 of iterations are completed

- cmd/kube-burner/ocp-config/alerts.yml
> Add node name to crio/kubelet alert

- cmd/kube-burner/ocp-config/alerts.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/cluster-density-ms.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/configmap.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/deployment.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/imagestream.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/route.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/secret.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/service.yml
- cmd/kube-burner/ocp.go
- docs/ocp.md
- pkg/workloads/workloads.go
- test/run-ocp.sh
We need this workload as a requirement for managed services based scenarios. Context at https://github.com/cloud-bulldozer/e2e-benchmarking/pull/545
> Cluster-density managed-services edition

- pkg/burner/create.go
- pkg/burner/job.go
- pkg/measurements/factory.go
Some cleanup in the job.go file
> Create WaitGroup in factory

- cmd/kube-burner/ocp-config/cluster-density-ms/configmap.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/deployment.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/secret.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/configmap.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/deployment-client.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/deployment-server.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/secret.yml
- cmd/kube-burner/ocp-config/cluster-density/configmap.yml
- cmd/kube-burner/ocp-config/cluster-density/deployment.yml
- cmd/kube-burner/ocp-config/cluster-density/secret.yml
- docs/configuration.md
- pkg/burner/pre_load.go
- pkg/util/template.go
- test/kube-burner-delete.yml
The custom template functions are already provided by the sprig library
> Deprecate custom template functions

- pkg/burner/create.go
- pkg/burner/job.go
- pkg/burner/patch.go
- pkg/burner/pre_load.go
- pkg/burner/utils.go
- pkg/burner/waiters.go
This allows to remove some lines
> Embed config.Object struct into object

- .github/workflows/docs.yml
- .gitignore
Based on mkdocs-material implementation
https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
Fixes: #321
> Workflow to update documentation on push event

- cmd/kube-burner/kube-burner.go
- docs/reference/configuration.md
- pkg/burner/job.go
- pkg/burner/waiters.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/measurements/factory.go
- pkg/measurements/pod_latency.go
- pkg/measurements/vmi_latency.go
- pkg/prometheus/prometheus.go
- pkg/util/metrics/metrics.go
- pkg/util/metrics/types.go
- pkg/workloads/helpers.go
It helps to reduce the number of arguments passed to some methods
> Adding UUID to config spec

- .github/workflows/pullrequest.yml
- README.md
Also adding push trigger to workflow
> Update status badge

- .github/workflows/builders.yml
- .github/workflows/image-upload.yml
- .github/workflows/stale.yml
- docs/index.md
> Set-up stale workflow

- .github/workflows/docs.yml
- .github/workflows/release.yml
- docs/development/ci.md
- docs/development/ci/release.md
It should be when a release is published
> Update docs deployment event 

- .github/workflows/builders.yml
- .github/workflows/docs.yml
- .github/workflows/gorelease.yml
- .github/workflows/image-upload.yml
It should solve cache restore issues. i.e: https://github.com/spf13/viper/actions/runs/4627151695/jobs/8184733172
```console
Warning: Restore cache failed: Dependencies file is not found in /home/runner/work/kube-burner/kube-burner. Supported file pattern: go.sum
```
> Checkout before setup

- .github/workflows/docs.yml
- .github/workflows/release.yml
> Deploy docs on tag push event

- .github/workflows/pullrequest.yml
- .github/workflows/test-k8s.yml
- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/patch.go
- pkg/burner/utils.go
- test/.gitignore
- test/test-ocp.bats
The linters workflow was fetching base branch commit 🤦🏽‍♂️ 
- Closes #
> Fetch PR commit in linters

- .golangci.yml
- .pre-commit-config.yaml
- pkg/burner/create.go
Adding gofmt and govet
- Closes #
> Extra linters

- cmd/kube-burner/ocp-config/metrics-report.yml
> Fix container name typo

- cmd/kube-burner/ocp-config/metrics-report.yml
> Replace container_cpu_system_seconds_total by container_cpu_usage_seconds_total

- .github/workflows/docs.yml
- .github/workflows/gorelease.yml
- .goreleaser.yml
There was some deprecations in the latest version of goreleaser.
- Closes #
> Fix gorelease and deploy docs workflow

- cmd/kube-burner/ocp-config/metrics-report.yml
Adding missing metrics to the report profile.
- Closes #
> Missing metrics

- go.mod
- go.sum
Bumping go-commons version. cc @afcollins 
- Closes #
> Bump go-commons

- cmd/kube-burner/ocp-config/cluster-density-v2/build.yml
Add pod resource requests to cluster-density build pods so they are distributed more evenly.
> Add resources to build to promote more even scheduling

- README.md
- docs/index.md
- docs/observability/indexing.md
Updated docs by checking the back-compatibility of OpenSearch with elastic search. Updated framework to toolset.
- Related Issue #335 
- Closes #
> Opensearch docs

- ROADMAP.md
Adding a ROADMAP.md
- Closes #
> Adding a ROADMAP.md

- examples/workloads/api-intensive/api-intensive.yml
- examples/workloads/cluster-density/cluster-density.yml
- examples/workloads/kubelet-density-cni-networkpolicy/kubelet-density-cni-networkpolicy.yml
- examples/workloads/kubelet-density-cni/kubelet-density-cni.yml
- examples/workloads/kubelet-density-heavy/kubelet-density-heavy.yml
- examples/workloads/kubelet-density/kubelet-density.yml
- examples/workloads/kubevirt-density/kubevirt-density.yml
> Update config files for examples

- .github/workflows/builders.yml
- .github/workflows/pullrequest.yml
- .github/workflows/test-k8s.yml
- docs/contributing/pullrequest.md
Also remove report_results job as it doesn't work well and add a couple of extra steps to build docs on PRs
- Closes #
> Use ./ with relative include paths

- ocp-config
Remove ocp-config symlink from root directory
Remove symlink from top level directory structure as it is not needed.
- Closes #
> Remove ocp-config from

- .goreleaser.yml
New versions get generated by goreleaser, updating the `version` package path is also required in its config.
Validation:
```shell
$ goreleaser build  --skip-validate --clean                             
• starting build...                                                                                                  
• loading config file                              file=.goreleaser.yml
• loading environment variables            
• getting and validating git state             
• building...                                    commit=845376bb3964d78d3d45db3f4f90d621a0a5aac3 latest tag=v1.7.5                                                                                                                        
• pipe skipped                                   reason=validation is disabled …
```
> Version goreleaser

- cmd/kube-burner/ocp-config/metrics-aggregated.yml
- cmd/kube-burner/ocp-config/metrics.yml
See https://github.com/cloud-bulldozer/e2e-benchmarking/pull/615 for context
> Added replicaset tracking to metrics

- ROADMAP.md
> Updating ROADMAP.md

- docs/contributing/index.md
- docs/contributing/tests.md
- docs/observability/alerting.md
- docs/ocp.md
This PR updates the documentation and fixes minor nits
As of reading this GitHub Doc's page https://cloud-bulldozer.github.io/kube-burner/v1.7.5/ 
has some broken links.
- Closes #
> Documentation updates

- docs/observability/indexing.md
- docs/reference/configuration.md
- mkdocs.yml
> fixing docs for indexing section

- cmd/kube-burner/ocp-config/metrics-aggregated.yml
- cmd/kube-burner/ocp-config/metrics.yml
Adding back pod distribution query to count Running pods
> Adding pod distribution query

- cmd/kube-burner/ocp-config/metrics-report.yml
Adding missing `name!=""` filter to prevent fetching double values
- Closes #460
> Add missing name!= filter to report metrics

- cmd/kube-burner/ocp-config/metrics-aggregated.yml
- cmd/kube-burner/ocp-config/metrics.yml
> Add missing by node aggregation

- mkdocs.yml
Limiting docs only upto latest 3 versions.
- Related Issue # 
- Closes # https://github.com/cloud-bulldozer/kube-burner/issues/418
This change can only be testing once merged into main and cut a release.
> Adding limit on docs version

- cmd/kube-burner/ocp-config/networkpolicy-matchexpressions/networkpolicy-matchexpressions.yml
- cmd/kube-burner/ocp-config/networkpolicy-matchlabels/networkpolicy-matchlabels.yml
- cmd/kube-burner/ocp-config/networkpolicy-multitenant/networkpolicy-multitenant.yml
- pkg/measurements/pod_latency.go
- pkg/workloads/helpers.go
- pkg/workloads/networkpolicy.go
Fixing bugs that were introduced as part of network policy workload.
##Related Issues
* https://github.com/cloud-bulldozer/kube-burner/issues/470
* https://github.com/cloud-bulldozer/kube-burner/issues/473
Tested on self-managed cluster using the below command
```
kube-burner ocp networkpolicy-multitenant --iterations 5
```
> bug fix in networkpolicy workload changes

- cmd/kube-burner/ocp.go
- docs/ocp.md
- pkg/workloads/helpers.go
- test/test-ocp.bats
Implementing profile-type to allow specifying the type of metrics profile to use in a single run
- Closes #479
> Implementing profile-type

- pkg/prometheus/prometheus.go
Capturing start time metrics for instant queries. For example if we have a metric with name `xyz` in metrics.yml we can look at its start value with name `xyz-start` and end value with name `xyz`.
- Related Issue # - https://github.com/cloud-bulldozer/kube-burner/issues/482
Tested on self managed cluster.
Collected metrics: [collected-metrics.tar.gz](https://github.com/cloud-bulldozer/kube-burner/files/12826278/collected-metrics.tar.gz)
```
[vchalla@vchalla-thinkpadp1gen2 collected-metrics-7b64fb77-fba4-4145-a70b-2792727adfac]$ cat secretCount.json  | jq '.[] | .value'
1105
1099
[vchalla@vchalla-thinkpadp1gen2 collected-metrics-7b64fb77-fba4-4145-a70b-2792727adfac]$ cat secretCount-start.json  | jq '.[] | .value'
1099
1187
```
> Capturing start metric for instant queries

- docs/observability/metrics.md
Let's try to document any new feature/relevant change we add. RE https://github.com/cloud-bulldozer/kube-burner/pull/489
- Closes #
> Missing documentation

- cmd/kube-burner/ocp-config/metrics-report.yml
- pkg/burner/metadata.go
s/endDate/elapsedTime
- Closes #
> Fix field name typo

- pkg/burner/create.go
Not-namespaced objects need different log messages
- Closes #
> Not namespaced objects log messages

- cmd/kube-burner/ocp-config/cluster-density-ms/deployment.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/service.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/deployment-client.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/deployment-server.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/np-allow-from-clients.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/service.yml
- cmd/kube-burner/ocp-config/cluster-density/deployment.yml
- cmd/kube-burner/ocp-config/cluster-density/service.yml
- cmd/kube-burner/ocp-config/networkpolicy-matchexpressions/networkpolicy-matchexpressions.yml
- cmd/kube-burner/ocp-config/networkpolicy-matchlabels/networkpolicy-matchlabels.yml
- cmd/kube-burner/ocp-config/networkpolicy-multitenant/networkpolicy-multitenant.yml
- cmd/kube-burner/ocp-config/node-density-cni/curl-deployment.yml
- cmd/kube-burner/ocp-config/node-density-cni/webserver-deployment.yml
- cmd/kube-burner/ocp-config/node-density-heavy/app-deployment.yml
- cmd/kube-burner/ocp-config/node-density-heavy/postgres-deployment.yml
- cmd/kube-burner/ocp-config/node-density/pod.yml
- cmd/kube-burner/ocp-config/pvc-density/pvc-density.yml
- docs/reference/configuration.md
- pkg/burner/job.go
- pkg/config/types.go
- pkg/measurements/pod_latency.go
- pkg/prometheus/prometheus.go
Cherry-picking #491 and #497
- Closes #
> Cherrypicking

- mkdocs.yml
> Remove duped section from docs

- pkg/burner/waiters.go
The number of client-side throttling messages has been reduced, but still seeing some. We should make the limiter to wait in a per request basis rather than a per-namespace basis
> Rate limit per clientSet request and not per namespace

- cmd/kube-burner/ocp-config/cluster-density-v2/build.yml
- cmd/kube-burner/ocp-config/cluster-density/build.yml
- examples/workloads/cluster-density/templates/build.yml
- mkdocs.yml
- pkg/burner/create.go
Cherry-picking:
- #503 
- #508 
- #506 
- Closes #
> Rebase 1.7

- .github/workflows/builders.yml
- .github/workflows/ci-tests.yml
- .github/workflows/docs.yml
- .github/workflows/gorelease.yml
- .github/workflows/image-upload.yml
- .github/workflows/linters.yml
- .github/workflows/release.yml
- .github/workflows/test-k8s.yml
Make CI tests a requirement before cutting a new release. It should help to prevent generating invalid releases based on branches that don't require PRs
- Closes #
> ci-tests are now a requirement of the release workflow

- go.mod
- go.sum
2 Interesting fixes are included:
- https://github.com/cloud-bulldozer/go-commons/pull/39
- https://github.com/cloud-bulldozer/go-commons/pull/36
- Closes #
> Bumping go-commons to 1.0.12

- .github/workflows/test-k8s.yml
- test/helpers.bash
- test/k8s/kube-burner-delete.yml
- test/test-k8s.bats
- test/test-ocp.bats
Removing bats run from tests and adding a new helper `run_cmd` to print the command before running it
- Closes #543
> Remove bats run

- .github/workflows/test-k8s.yml
- Makefile
- test/helpers.bash
- test/k8s/kube-burner-delete.yml
- test/k8s/kube-burner.yml
- test/test-k8s.bats
k8s testing was a bit outdated,
- Closes #
> Refactor k8s tests

- README.md
- docs/index.md
Required for cncf onboarding
- Closes #
> Reference CODE_OF_CONDUCT.md in README

- ROADMAP.md
Updated links from cloud-bulldozer project to kube-burner
> Update roadmap links with new project name

- cmd/kube-burner/ocp-config/metrics-report.yml
Adding max aggregated memory usage for some components:
- kubelet
- crio
- kube-apiserver
- openshift-apiserver
- etcd
- Closes #
> Adding maximum aggregated memory metrics

- cmd/kube-burner/ocp-config/metrics-report.yml
> Max aggregated for kube-controller-manager

- cmd/kube-burner/ocp-config/metrics-report.yml
1. Report api calls latency
2. Report max aggregated memory usage of masters, workers and infra nodes
> report api calls latency

- pkg/burner/waiters.go
waitNs must be defaulted on a per object basis
- Closes #
> Set waitNs in each iteration

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- docs/contributing/index.md
- docs/contributing/pullrequest.md
- docs/contributing/release.md
- docs/contributing/tests.md
- mkdocs.yml
The CI docs were a bit outdated
- Closes #
> Update CI documentation

- docs/cli.md
- pkg/prometheus/types.go
- pkg/util/metrics/metrics.go
- pkg/workloads/helpers.go
Permit basic authentication for metrics endpoint
- Closes #
> Permit basic authentication in metrics endpoint

- pkg/util/metrics/tarball.go
- test/test-k8s.bats
Log lines were incorrect and we didn't have any test
- Closes #
> Metrics tarball improvements and test

- .github/workflows/builders.yml
- .github/workflows/docs.yml
- .github/workflows/gorelease.yml
- .github/workflows/image-upload.yml
- .github/workflows/test-k8s.yml
Updating deprecated node16 actions
- Closes #
> Node 20 in GHA

- test/k8s/kube-burner.yml
- test/test-k8s.bats
Remove pods created by the previous test in the default namespace
> Garbage collect pods in default namespace

- docs/reference/configuration.md
- go.mod
- go.sum
- pkg/burner/create.go
- pkg/burner/job.go
- pkg/config/config.go
- pkg/config/types.go
- test/k8s/kube-burner.yml
- test/test-k8s.bats
Adding churnCycles as an option for churning.
- Related Issue: https://github.com/kube-burner/kube-burner/issues/592
- Closes: https://issues.redhat.com/browse/PERFSCALE-2842
Tested integrated with https://github.com/kube-burner/kube-burner-ocp/pull/16
> Adding churnCycles as an option for churning

- go.mod
- go.sum
Includes fix https://github.com/cloud-bulldozer/go-commons/pull/42
cc:  @mukrishn 
- Closes #
> go-commons 1.0.14

- docs/observability/indexing.md
- examples/workloads/kubelet-density-heavy/templates/app-deployment.yml
- pkg/burner/pre_load.go
- test/k8s/kube-burner-delete.yml
Using multi-architecture container images for perfapp and pause.
- Related Issue #605
- Closes
> Using multi architecture container images for perfapp and pause

- docs/reference/configuration.md
As a result of this slack [thread](https://redhat-internal.slack.com/archives/C05CDC19ZKJ/p1710510088455179), updating README.md for churn usage.
> Updating README.md for churn usage

- examples/workloads/api-intensive/api-intensive.yml
- examples/workloads/cluster-density/cluster-density.yml
- examples/workloads/crd-scale/crd-scale.yml
- examples/workloads/kubevirt-density/kubevirt-density.yml
https://github.com/kube-burner/kube-burner/pull/611 added `metricsEndpoints`. Update examples to fix the error.
```
level=fatal msg="Config error: error decoding configuration file: yaml: unmarshal errors:\n  line 2: field indexers not found in type config.Spec" file="kube-burner.go:97"
```
- Closes #
> update metricsEndpoints in examples

- pkg/config/types.go
- pkg/util/metrics/metrics.go
- pkg/workloads/helpers.go
My mistake, kube-burner-ocp doesn't work well with the latest changes pushed in https://github.com/kube-burner/kube-burner/pull/611
- Closes #
> Embedconfig bugfixes

- examples/workloads/kubelet-density-cni-networkpolicy/templates/curl-deployment.yml
- examples/workloads/kubelet-density-cni-networkpolicy/templates/webserver-deployment.yml
- examples/workloads/kubelet-density-cni/templates/curl-deployment.yml
- examples/workloads/kubelet-density-cni/templates/webserver-deployment.yml
- examples/workloads/kubelet-density-heavy/templates/app-deployment.yml
- examples/workloads/kubelet-density-heavy/templates/postgres-deployment.yml
spec.triggers is something openshift specific
> Remove triggers from examples

- pkg/alerting/alert_manager.go
Requires the same fallback logic for alerts profile as well: https://github.com/kube-burner/kube-burner/pull/643
CI tests and needs to be tested with ocp wrapper and e2e.
> Adding fallback logic for alert profile

- pkg/burner/job.go
- pkg/burner/metadata.go
Indexing jobSummary for index job as well
- Closes # https://github.com/kube-burner/kube-burner-ocp/issues/76
Tested integrating with ocp-wrapper: https://github.com/kube-burner/kube-burner-ocp/pull/81
> Making changes to add jobSummary support for custom jobs

- examples/workloads/kubevirt-density/kubevirt-density.yml
> Remove env var

- pkg/util/metrics/metrics.go
Fixing NPE for PR-661. This issue occurred while testing with ocp-wrapper.
> Fixing NPE for PR-661

- cmd/kube-burner/kube-burner.go
- pkg/util/utils.go
- test/helpers.bash
- test/test-k8s.bats
Adds log output as a file
- Related Issue #641 
- Closes #
> Log output

- pkg/burner/metadata.go
Making version optional for `jobSummary` so that it will not be present in tools that don't require it.
> Making version optional

- pkg/measurements/metrics/metrics.go
- pkg/measurements/pod_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/vmi_latency.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
Adding job name back to metrics.
- Closes #668
> Add jobName to metrics

- docs/reference/configuration.md
- pkg/burner/create.go
- pkg/burner/patch.go
- pkg/config/types.go
Gives the user control of how missing keys are handled, allowing users to use defaults in there templates.
- Closes #676
> Allow users to define templating options for jobs

- docs/cli.md
fixed links and text chapter reference
- Closes #685
> fix 404 in cli.md

- pkg/measurements/factory.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
- pkg/measurements/service_latency.go
- pkg/measurements/vmi_latency.go
Remove unnecessary validateConfig() from measurements interface 
- Closes #
> Remove validateConfig()

- pkg/alerting/alert_manager.go
- pkg/prometheus/prometheus.go
When the embedded file is not found, we should use the original location in the log messages.
- Closes #
> Improve log messages for embedded configs

- cmd/kube-burner/kube-burner.go
- pkg/alerting/alert_manager.go
- pkg/burner/job.go
- pkg/measurements/common.go
- pkg/measurements/node_latency.go
- pkg/measurements/pod_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/vmi_latency.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- pkg/util/metrics/metrics.go
- pkg/util/metrics/types.go
- pkg/workloads/helpers.go
- pkg/workloads/types.go
These changes are required to support indexing a different subset of metadata fields the indexed metrics different than jobSummary
- Closes #
> Implement summary and metrics metadata fields

- pkg/util/metrics/metrics.go
Let's check these maps are initialized before using them to prevent potential issues
- Related Issue https://github.com/kube-burner/kube-burner-ocp/pull/120
- Closes #
> Check if map is initialized prior using it

- pkg/burner/consts.go
- pkg/burner/pre_load.go
- pkg/burner/utils.go
- pkg/burner/waiters.go
- allows the processing of StatefulSets by adding labels to both the template and the selector
- fetch the images for pre-loading
- Closes #
> Better support StatefulSet

- .gitignore
Running tests locally creates many log files that git should ignore
> Add test output files to git ignore list

- .github/workflows/test-k8s.yml
This is only a preparation for the next PR to allow making changes to the GitHub workflow
> GH Action - Set TEST_BINARY in preparation

- pkg/burner/utils.go
kube-burner copies the labels of its created objects into the template of the underlying object (e.g. pod template of a deployment). These labels are then used in other places in the code. For example, metrics measurements rely on the existence of the `kube-burner-runid` label on the pod (or VMI in case of VMs).
In the original code, the labels were copied only if the labels field already existed. 
With these fix, for specific kinds, the labels are copied even if none were added.
- Closes #736
> Copy the labels to the underlying template even if it does not have any

- pkg/burner/utils.go
Let's try to make the info output a little less verbose
- Closes #
> Decrease object verify logging level

- docs/wrappers/wrappers.md
- mkdocs.yml
- pkg/util/template.go
New method to import custom rendering template functions from external implementations.
- Closes #
> Add method to import custom template rendering functions

- docs/measurements/index.md
- pkg/burner/create.go
- pkg/config/types.go
- pkg/measurements/common.go
- pkg/measurements/pod_latency.go
- pkg/measurements/vmi_latency.go
Add the job iteration and replica count into the measurements JSON to allow post processing jobs to differentiate between iterations
> Pod and VMI Measurements: Add information about iteration and replica

- go.mod
- go.sum
> go-commons v1.0.18

- cmd/kube-burner/kube-burner.go
- docs/cli/index.md
- docs/reference/configuration.md
- pkg/alerting/alert_manager.go
- pkg/burner/create.go
- pkg/burner/object.go
- pkg/config/config.go
- pkg/measurements/netpol_latency.go
- pkg/prometheus/prometheus.go
- pkg/util/metrics/utils.go
- pkg/util/url_reader.go
- pkg/workloads/helpers.go
- test/k8s/kube-burner-userdata.yml
- test/k8s/objectTemplates/deployment-userdata-labels.yml
- test/k8s/objectTemplates/userdata-test.yml
- test/test-k8s.bats
Allow the user to pass input variables using a file in addition to environment variables
> User data input

- docs/measurements/index.md
- go.mod
- go.sum
- pkg/measurements/common.go
- pkg/measurements/vmi_latency.go
- test/k8s/kube-burner-virt.yml
There were lot of bugs and old code in this measurement, let's update it accordingly.
cc @jeniferh @ygalblum
- Closes #
> Vmi latency fixes

- docs/reference/configuration.md
- pkg/util/template.go
Allow reading data from a file into the rendered template
> Template - add ReadFile to template map

- pkg/burner/pre_load.go
- test/k8s/kube-burner-virt.yml
- test/k8s/kube-burner.yml
Preload Virtual machines images folowing the same mechanism we already do with pods
cc @jeniferh @ygalblum @jtaleric
> Preload vm images

- docs/measurements/index.md
- pkg/burner/utils.go
- pkg/measurements/datavolume_latency.go
- pkg/measurements/factory.go
- test/helpers.bash
- test/k8s/kube-burner-dv.yml
- test/k8s/objectTemplates/datavolume-clone.yml
- test/k8s/objectTemplates/vm-datavolume.yml
- test/test-k8s.bats
Allow users to keep track of `DataVolume` latencies
> Metrics - Add support for DataVolume latency

- pkg/alerting/alert_manager.go
Removing redundant loop in alerting logic. Optimizing the list appends with `...` ellipsis well know as spread operator in java.
Functionality test will be covered through CI runs in the PR itself.
> Optimizing alert logic using ellipsis

- .github/workflows/test-k8s.yml
Fetch the latest patch version of the latest 3 minor versions of the kindest/node image and use them for testing
> CI - Run on latest patch version of the latest 3 minor version

- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/workflows/builders.yml
- .github/workflows/gorelease.yml
- .github/workflows/image-upload.yml
> Update to golang 1.23

- docs/reference/configuration.md
- pkg/burner/waiters.go
- pkg/config/types.go
- test/k8s/kube-burner-dv.yml
- test/k8s/kube-burner-sequential-patch.yml
- test/k8s/kube-burner-userdata.yml
- test/k8s/kube-burner.yml
Optimize waiters schema structure to better align with wide range of usecases. More context [here](https://github.com/kube-burner/kube-burner/issues/703#issue-2552313830).
Closes # https://github.com/kube-burner/kube-burner/issues/703
https://gist.github.com/vishnuchalla/15ce390451990328bd0e9daf6ff20c96
> Optimizing waiters structure for scalability

- README.md
- SECURITY.md
Documentation update
Adding security policy as per the guidelines [here](https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-incubation-application.md#security)
Closes # https://issues.redhat.com/browse/PERFSCALE-3726
> Adding security policy

- .github/workflows/ci-tests.yml
- .github/workflows/codql.yml
- CI
Adding codeql for static code analysis: https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-incubation-application.md#security
Closes # https://issues.redhat.com/browse/PERFSCALE-3726
> Adding codeql for static analysis

- .github/workflows/codeql.yml
- pkg/measurements/pvc_latency.go
- test/k8s/kube-burner-dv.yml
- test/k8s/objectTemplates/datavolume-clone.yml
- test/k8s/objectTemplates/vm-datavolume.yml
- Bug fix
- CI
Code changes:
- PVC Latency - do not count missed pending phase as error
Test changes:
- Pin the container tag and align volume sizes
- Fix waiter path and labelSelector
- Reduce wait times
> Fix DV and PVC Latency test

- pkg/burner/conditions.go
- pkg/burner/kubevirt.go
- Bug fix
Start Paused - Wait for paused condition
Restart - make sure the new conditons timestamp is later
> Kubevirt - fix wait conditions

- pkg/measurements/datavolume_latency.go
- Optimization
DV Latency - reduce log verbosity of ready to debug
> DV Latency - reduce log verbosity

- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/executor.go
- pkg/burner/namespaces.go
- pkg/burner/object.go
- pkg/burner/patch.go
- pkg/burner/utils.go
- pkg/burner/waiters.go
- test/k8s/kube-burner-virt-operations.yml
- Optimization
Change objects array to hold pointers and pass by pointer
Remove duplicate kind field in object struct
Fix data volume latency test
> Allow changing the content of the objects stored in the objects array

- docs/reference/configuration.md
- pkg/burner/job.go
- pkg/config/types.go
- test/helpers.bash
- test/k8s/kube-burner-metrics-aggregate.yml
- test/test-k8s.bats
- Optimization
Allow aggregating metrics from consecutive jobs so that metrics accumulation can span over multiple jobs
> Metrics - allow aggregating metrics from consecutive jobs

- ADOPTERS.md
Adding ADOPTERS.md as a part of guidelines [here](https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-incubation-application.md#required-5)
- Related Issue # https://issues.redhat.com/browse/PERFSCALE-3698
> Adding ADOPTERS.md template

- pkg/measurements/common.go
- pkg/measurements/datavolume_latency.go
- pkg/measurements/netpol_latency.go
- pkg/measurements/node_latency.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
- pkg/measurements/pvc_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/snapshot_latency.go
- pkg/measurements/vmi_latency.go
- Optimization
Some symbol names were not 100% correct
- Closes #
> Rename some measurement symbols

- cmd/kube-burner/kube-burner.go
- docs/cli/index.md
- pkg/config/config.go
- pkg/util/metrics/types.go
Adding --configmap argument back under kube-burner init sub command
```shell
/kube-burner init --configmap kube-burner-config-smanda -n burner
time="2024-10-15 08:07:38" level=info msg="Fetching configmap kube-burner-config-smanda" file="config.go:201"
time="2024-10-15 08:07:39" level=info msg="🔥 Starting kube-burner (configmap@38fcb39d684d5401517073093d95c6d553d95cb4) with UUID d8c3a0f6-7229-4b1d-95e0-ef2706a15ff0" file="job.go:110"
time="2024-10-15 08:07:40" level=info msg="Job cluster-density-v2: 1 iterations with 1 Deployment replicas" file="create.go:92"
time="2024-10-15 08:07:40" level=info msg="QPS: 20" file="job.go:131"
time="2024-10-15 08:07:40" level=info msg="Burst: 20" file="job.go:132"
time="2024-10-15 08:07:40" level=info msg="Triggering job: cluster-density-v2" …
```
> Adding --configmap argument back under kube-burner init sub command

- pkg/burner/job.go
- Bug fix
Fixing the expression
- Closes #854
> Fix churnEnd calculation

- docs/reference/configuration.md
- examples/workloads/cluster-density/cluster-density.yml
- examples/workloads/cluster-density/templates/deployment.yml
- examples/workloads/cluster-density/templates/envs.tpl
- pkg/burner/executor.go
- pkg/burner/pre_load.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/measurements/netpol_latency.go
- pkg/util/metrics/utils.go
- pkg/util/template.go
- test/k8s/kube-burner-delete.yml
- test/k8s/kube-burner-sequential-patch.yml
- test/k8s/kube-burner.yml
- test/k8s/objectTemplates/deployment.yml
- test/k8s/objectTemplates/envs.tpl
- New feature
Add the ability to supply a list of paths to sub templates that are then supplied to all object templates. 
- Related Issue #674
- Closes #674 
Tested and verified the changes in local. Able to see the rendering working as expected for the deployment.
```
"spec": {
"containers": [
{
"args": [
"sleep",
"infinity"
],
"env": [
{
"name": "ENVVAR1_deployment-pod",
"value": "55d897a9c68ea8a48e59f5ec9cf40aa7ffbdfd33e40bf71ee0ffdba1611518586015791965693165b030b20af4d0979a83d098fcf289e9e9fcbb170df5b144314f3d8d5c0755e0415ed5f8ec53a20f0ac8344e719e0993b3ddecd1d6e7b5f9a4b4cf78c9b9a6f328d754d955d897a9c68ea8a48e59f5ec9cf40aa7ffbdfd33e40bf71ee0ffdba1611518586015791965693165b030b20af4d0979a83d098fcf289e9e9fcbb170df5b144314f3d8d5c0755e0415ed5f8ec53a20f0ac8344e719e0993b3ddecd1d6e7b5f9a4b4cf78c9 …
```
> Add function templating feature

- docs/measurements/index.md
- pkg/measurements/factory.go
- pkg/measurements/job_latency.go
- pkg/measurements/pod_latency.go
- test/k8s/kube-burner.yml
- test/k8s/objectTemplates/job.yml
- test/test-k8s.bats
- New feature
New Job latency measurement to track job's completion and start time. Required for my ongoing Kueue work  https://github.com/cloud-bulldozer/kueue-scale/
- Closes #
> Job latency measurement

- cmd/kube-burner/kube-burner.go
- pkg/burner/create.go
- pkg/burner/executor.go
- pkg/burner/kubevirt.go
- pkg/burner/metadata.go
- pkg/burner/pre_load.go
- pkg/burner/utils.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/measurements/datavolume_latency.go
- pkg/measurements/factory.go
- pkg/measurements/metrics/metrics.go
- pkg/measurements/netpol_latency.go
- pkg/measurements/node_latency.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
- pkg/measurements/pvc_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/types/types.go
- pkg/measurements/vmi_latency.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- pkg/util/metrics/metrics.go
- pkg/util/metrics/tarball.go
- pkg/util/metrics/types.go
- pkg/util/template.go
- pkg/util/userMetadata.go
- pkg/util/utils.go
- Optimization
After running:
```shell
$ go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix ./...
```
- Closes #
> Modernize golang code

- GOVERNANCE.md
Add developers meeting info to doc
- Closes #
> Add developers meeting info to doc

- pkg/alerting/alert_manager.go
- pkg/measurements/base_measurement.go
- pkg/measurements/datavolume_latency.go
- pkg/measurements/job_latency.go
- pkg/measurements/node_latency.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pvc_latency.go
- pkg/measurements/snapshot_latency.go
- pkg/measurements/vmi_latency.go
- pkg/workloads/helpers.go
These methods must be public so they can be used in external measurements implementations,
- Closes #
> Public methods

- cmd/kube-burner/kube-burner.go
- pkg/burner/job.go
- pkg/measurements/base_measurement.go
- pkg/measurements/base_measurement_factory.go
- pkg/measurements/datavolume_latency.go
- pkg/measurements/factory.go
- pkg/measurements/job_latency.go
- pkg/measurements/netpol_latency.go
- pkg/measurements/node_latency.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
- pkg/measurements/pvc_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/snapshot_latency.go
- pkg/measurements/vmi_latency.go
- Bug fix
We need to pass an instance of the embedCfg so it can read the network policy templates
- Closes #
> Fix network policy measurement

- examples/workloads/cluster-density/templates/deployment.yml
Bug Fix
Changed image in deployment.yml 
- Related Issue #847
>  [Bug Fix] Changed image in deployment.yml

- docs/reference/configuration.md
- pkg/burner/job.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/prometheus/prometheus.go
- Optimization
Let's try to use constants and log the metricsClosing option selected. And also let's update the default metricsClosing value to `afterJobPause` to keep previous behaviour. 
- Closes #
> Improve metricsClosing logic and update default value

- .golangci.yml
- .pre-commit-config.yaml
- pkg/burner/job.go
- pkg/burner/kubevirt.go
- pkg/config/config.go
- pkg/measurements/common.go
- pkg/measurements/datavolume_latency.go
- pkg/measurements/job_latency.go
- pkg/measurements/netpol_latency.go
- pkg/measurements/node_latency.go
- pkg/measurements/pod_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/snapshot_latency.go
- pkg/util/metrics/tarball.go
- pkg/util/namespaces.go
- pkg/util/utils.go
- CI
migrated to golangci-lint version 2.1.6
- Closes #899
> migrated to golangci-lint version 2.1.6

- pkg/burner/delete.go
- pkg/burner/kubevirt.go
- pkg/burner/object.go
- pkg/burner/patch.go
- pkg/burner/read.go
- Bug fix
Fix Object to read from Workload dir and not from Metrics
Pass embedFS
> Object - read object template from Workload dir

- docs/reference/configuration.md
- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/executor.go
- pkg/burner/job.go
- pkg/burner/kubevirt.go
- pkg/burner/namespaces.go
- pkg/burner/patch.go
- pkg/burner/pre_load.go
- pkg/burner/read.go
- pkg/burner/utils.go
- pkg/burner/waiters.go
- pkg/config/config.go
- pkg/config/types.go
- test/k8s/kube-burner.yml
- test/test-k8s.bats
- New feature
Adding the functionality to conduct a garbage-collection on a per-job basis.
Also renaming some variables and functions to improve code quality
- Closes #
> [RFE] Per job garbage collection feature

- pkg/burner/kubevirt.go
- Bug fix
Use the rate limiter in the kubevirt job type
> kubevirt jobs - add rate limiter

- pkg/measurements/vmim_latency.go
- Bug fix
Fix VMIM latency to use the new MeasurementWatcher API
> VMIM Latency - adjust to new MeasurementWatcher

- Makefile
- docs/contributing/index.md
Added commands in docs to copy the binary to the local bin directory. Also updated the make build command to do the same.
- Related Issue #942
- Closes #942
> Add install command to docs

- pkg/workloads/helpers.go
- Optimization
The current logic does not handle file read errors correctly.
The PR also simplifies the overall function logic to receive directory names rather than loose files.
- Related Issue https://github.com/kube-burner/kube-burner-ocp/issues/300
- Closes #
> Handle file read errors

- CONTRIBUTING.md
- CONTRIBUTOR_LADDER.md
Added community ladder Document
- Adds requirements to become member, contributor and maintainer
We can always tweak what we expect from people
- Closes #
> Adds contributor ladder document

- pkg/burner/kubevirt.go
- Bug fix
kubevirt UnPause - wait for Pause condition to disappear
- Closes #981
> kubevirt UnPause - wait for Pause condition to disappear

- docs/measurements/index.md
- pkg/config/config.go
- pkg/config/types.go
- pkg/measurements/factory.go
- test/k8s/kube-burner-measurements.yml
- test/test-k8s.bats
- New feature
introduces job-specific measurements along side global ones
- Job-specific measurements will combine with existing global ones, ensuring backward compatibility
- Global measurements will apply to all jobs; if a job defines the same measurement, global measurements will be skipped
-  Documentation updated for measurements
- Tests added for measurements
- Logs for job-specific measurements have been added
- Related Issue
- Closes #715
> feat(job): add support for job-specific measurements
