kube-burner/kube-burner

- cmd/kube-burner.go
- pkg/burner/burner.go
- pkg/burner/namespaces.go
Among others, with this change we avoid triggering all goroutines at the same time in not-namespaced tests, so objects are now created in ascending order.
> Code optimizations

- README.md
- pkg/measurements/pod_latency.go
PodLatency was measured using pod conditions, however the status of these conditions wasn't verified, so they could be False.
> Fix podLatency measurement

- cmd/kube-burner.go
- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/job.go
- pkg/burner/metadata.go
- pkg/config/config.go
- pkg/measurements/factory.go
- pkg/measurements/pod_latency.go
- pkg/prometheus/prometheus.go
benchmarks all metrics were tagged with the name of the first job.
With this change metrics are now tagged to the right job depending on their timestamp.
In addition, when triggering now kube-burner index, kube-burner metrics ara tagged with the jobName "kube-burner-indexing".
Some log messages have been improved as well.
> Multi-job metric collection improvements

- pkg/burner/create.go
- pkg/burner/namespaces.go
Executing kubelet-density with a wrong cofiguration file leads into semaphore acquire issues
```
ERRO[2021-01-22 17:35:27] Pod/kubelet-density-25 in namespace kubelet-density already exists                           
ERRO[2021-01-22 17:35:27] Pod/kubelet-density-25 in namespace kubelet-density already exists                                                                                                                                                  
ERRO[2021-01-22 17:35:27] Pod/kubelet-density-25 in namespace kubelet-density already exists                           
ERRO[2021-01-22 17:35:27] Pod/kubelet-density-25 in namespace kubelet-density already exists …
```
> Fix semaphore error when accesing to labels map and improve namespace creation error handling

- docs/configuration.md
- pkg/config/config.go
- pkg/indexers/elastic.go
- pkg/indexers/factory.go
- pkg/util/url_reader.go
- test/base.sh
- test/kube-burner.yml
Use go-template to render configuration file. This allow kube-burner to reference environment variables in the configuration.
> Use go-template to render configuration file

- .github/workflows/go.yml
- pkg/burner/create.go
- pkg/burner/utils.go
- pkg/config/config.go
- pkg/util/template.go
Move the template rendering code to the util package to be reused in the main config rendering.
> Take advantage of the custom template functions in the main config rendering

- cmd/kube-burner/kube-burner.go
Pausing job before indexing metadata
> Pause before sending metadata

- pkg/burner/create.go
- pkg/burner/namespaces.go
According to the docs
```
// ExponentialBackoff repeats a condition check with exponential backoff.
//
// It repeatedly checks the condition and then sleeps, using `backoff.Step()`
// to determine the length of the sleep and adjust Duration and Steps.
// Stops and returns as soon as:
// 1. the condition check returns true or an error,
// 2. `backoff.Steps` checks of the condition have been done, or
// 3. a sleep truncated by the cap on duration has been completed.
// In case (1) the returned error is what the condition function returned.
// In all other cases, ErrWaitTimeout is returned.
```
We must return false, nil if we want to retry a function
> Fix retry logic in create functions

- docs/cli.md
- docs/configuration.md
- docs/index.md
Reference external repository with more workloads, and clarify examples location, pointing to a folder rather than a file.
#79 
> Add more examples locations and clarify documentation

- Containerfile
Seems like latest microdnf builds require now the `-y` flag to behave 100% unattended
> Add -y flag to microdnf

- docs/measurements.md
- pkg/measurements/pprof.go
Base64 certificates fits better with e2e-benchmarking.
> Base64 certs

- docs/configuration.md
- pkg/config/config.go
- pkg/config/types.go
Also skipping annoying client-go klog output
```
W0604 10:46:01.769645    8048 client_config.go:559] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```
> Deprecate kubeconfig variable

- pkg/measurements/pod_latency.go
- test/run.sh
The first thing we have to do in stop() is closing the channel to stop the informer.
Prevents issues like:
```golang
time="2021-09-22 15:42:50" level=info msg="Stopping measurement: podLatency"                                                                                                                                                                                                    [232/1844]
fatal error: concurrent map iteration and map write                                                                                                                                                                                                                                       
goroutine 1 [running]: …
```
> Fix race condition when a pod status is updated and the channel is still opened

- cmd/kube-burner/kube-burner.go
- pkg/prometheus/prometheus.go
- test/run.sh
Collect metrics only once and detect to which job belong those metrics with the following logic.
```golang
for _, job := range jobList {
// If metric timestamp is lower than job end timestamp, we assume the datapoint belongs to that job
if val.Timestamp.Time().Before(job.End) {
jobName = job.Config.Name
}
}
```
- Fixes: https://github.com/cloud-bulldozer/kube-burner/issues/127
> Optimize metric collection in benchmarks with multiple jobs

- pkg/config/config.go
- pkg/measurements/pod_latency.go
Truncate namespaces with more than 63 characters
K8s does not allow to create namespaces with more than 63 characters.
> Truncate namespace

- cmd/kube-burner/kube-burner.go
- pkg/measurements/factory.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
Wait for all measurements to be running before creating any object
Fixes a race condition leading to miss some events in small benchmarks.
Running some quick tests with a tiny workload (3 pods):
- Without this patch:
```shell
$ kube-burner init -c kubelet-density.yml 
...
rsevilla@wonderland ~/labs/kube-burner $ grep sche collected-metrics/kubelet-density-podLatency.json   
"schedulingLatency": 0,                                                                                            
"schedulingLatency": 0,                                                                                            
"schedulingLatency": 0,  
$ kube-burner init -c kubelet-density.yml 
...
rsevilla@wonderland ~/labs/kube-burner $ grep sche …
```
> Wait for measurements initialization before creating objects

- cmd/kube-burner/kube-burner.go
- docs/configuration.md
- pkg/burner/namespaces.go
- pkg/burner/pre_load.go
- pkg/burner/utils.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/util/template.go
- test/kube-burner.yml
Pre load images implementation, this feature can help us to determine Pod latencies with higher precision. 
It follows the workflow below:
- Job-1 (ImagePreload is true)
-  Extract images from the job's object templates. Currently supported objects are Deployments, DaemonSets ReplicaSets, Jobs and Pods
- Create the kube-burner namespace
- Create DaemonSet(s) in the previous namespace (1 replica of these pods will be scheduled to all nodes of the cluster) using the extracted images, these DaemonSets consists of a initContainer one of the  the images extracted from the templates and a container using a pause image. The initContainer trick is used to prevent the RestartPolicy "Always" from the DS to generate too much noise in the nodes.
- …
> Pre load job images

- examples/workloads/kubelet-density-cni-networkpolicy/kubelet-density-cni-networkpolicy.yml
- examples/workloads/kubelet-density-cni-networkpolicy/templates/allow-http.yml
- examples/workloads/kubelet-density-cni-networkpolicy/templates/curl-deployment.yml
- examples/workloads/kubelet-density-cni-networkpolicy/templates/deny-all.yml
- examples/workloads/kubelet-density-cni-networkpolicy/templates/webserver-deployment.yml
- examples/workloads/kubelet-density-cni-networkpolicy/templates/webserver-service.yml
- examples/workloads/kubelet-density-cni/kubelet-density-cni.yml
- examples/workloads/kubelet-density-cni/templates/curl-deployment.yml
- examples/workloads/kubelet-density-cni/templates/webserver-deployment.yml
- examples/workloads/kubelet-density-cni/templates/webserver-service.yml
This uses a curl for the readinessprobe of the client pod which can
help measure CNI latency. We also no longer use a postgres
pod on the server side - that is replaced by a simple node.js
app. Also adds networkpolicy.
Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>
> Add CNI focused kubelet-density variants

- pkg/burner/namespaces.go
- pkg/burner/waiters.go
Kube-burner now waits for jobs completion and also the pod wait logic
has been optimized
- Fixes: #155
> Job wait mechanism

- examples/workloads/api-intensive/api-intensive.yml
I accidentally selected a different template for a patch example in the api-intensive config than I added to the folder. This fixes that.
Fixes #160
> Fix incorrect template for Patch api-intensive example

- pkg/burner/pre_load.go
Update to preload-kube-burner to prevent conflicts in OCP managed-services
deployments
> Preload namespace name

- pkg/indexers/elastic.go
- pkg/prometheus/prometheus.go
We usually don't need prometheus queries to be printed in info log level.
> Cut down info verbosity

- pkg/burner/pre_load.go
Older k8s versions does not create the previous label, so the preLoad
namespace it's not deleted after the preLoad period
> Update preLoad namespace selector

- examples/workloads/kubelet-density-cni-networkpolicy/templates/curl-deployment.yml
- examples/workloads/kubelet-density-cni/templates/curl-deployment.yml
Amend kubelet-density-cni and kubelet-density-cni-networkpolicy
examples for finer granularity.
Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>
> Reduce timeoutSeconds for startupProbe

- cmd/kube-burner/kube-burner.go
- pkg/burner/create.go
With the previous implementation, when the object verification failed and errorOnVerify was true, kube-burner exited instantaneously. With this new approach, kube-burner will set RC to 1, and will go forward to metrics indexing.
Recent OCP payloads based in k8s 1.24 are failing and skipping metrics indexing due to a API issue leading to fail object listing using labelSelectors (mechanism used by kube-burner in object verification under the hood): 
https://bugzilla.redhat.com/show_bug.cgi?id=2094012
> Set RC to 1 when object verification fails rather than exit

- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/namespaces.go
- pkg/burner/patch.go
- pkg/burner/pre_load.go
- pkg/burner/utils.go
The current exponentialBackoff wrapper uses hardcoded contants and we need to use higher values to delete namespaces.
> Configurable exponential backoff

- docs/configuration.md
- pkg/burner/create.go
- pkg/burner/namespaces.go
- pkg/burner/pre_load.go
- pkg/config/types.go
- test/kube-burner.yml
Due to recent changes in the pod security standards in OpenShift we
should be able to provide the option to add custom labels to namespaces created by
kube-buner in order to bypass those policies in our performance
benchmarks
Context -> https://github.com/cloud-bulldozer/e2e-benchmarking/issues/436
> Custom labels to namespaces

- pkg/measurements/pod_latency.go
- pkg/measurements/vmi_latency.go
We need to reset pod/vmi latency slices when the measurement is stopped to avoid indexing/writing data from previous jobs
- Fixes part of #181
> Reset latency slices when stopping measurement

- cmd/kube-burner/kube-burner.go
- docs/configuration.md
- pkg/burner/create.go
- pkg/config/config.go
- pkg/config/types.go
- test/kube-burner.yml
- test/run.sh
Adding the ability to "churn" (delete and recreate) a job in kube-burner.  Churn or the deletion and re-creation of objects, is supported for namespace based jobs only. This occurs after the job has completed but prior to uploading metrics, if applicable. It deletes a percentage of contiguous namespaces randomly chosen and re-creates them with all of the appropriate objects. It will then wait for a specified delay (or none if set to 0 however in testing this may have caused some back off  delays; setting a churn delay of a few seconds remedied that) before deleting and recreating the next randomly chosen set. This cycle continues until the churn duration has passed.
Example input and output:
Snip of input file:
```
jobs:
- name: cluster-density
jobIterations: 10
qps: 20
burst: 20 …
```
> Add churn ability

- pkg/prometheus/prometheus.go
Adding proxy settings when setting prometheus client if they exist
https://github.com/cloud-bulldozer/kube-burner/issues/192
> Proxy for prometheus

- .github/workflows/containers.yml
- .github/workflows/kube-burner.yml
- Containerfile
- Makefile
Container build fails using the --platform flag, https://github.com/cloud-bulldozer/kube-burner/actions/runs/3517872479/jobs/5896141950
Reverts #210 and #211
> Revert containers

- cmd/kube-burner/ocp.go
- pkg/discovery/discovery.go
- pkg/workloads/helpers.go
- pkg/workloads/node-density-cni.go
- pkg/workloads/node-density-heavy.go
- pkg/workloads/node-density.go
ClientSet is initialized even when running  `kube-burner version`. That's not desired, that command should be available offline
> Use a discoveryAgent go prevent creating clients on init()

- pkg/workloads/helpers.go
Skip TLS verification on cluster metadata indexing
> Skip TLS verification on cluster metadata indexing

- pkg/burner/create.go
- test/run-ocp.sh
The original implementation uses creates a new go-routine per replica, in scenarios where there's only one object replica per iteration (node-density), kube-burner might not reach the configured QPS ratio . This is more likely in scenarios where there're some delay from the API, like when network latency with the API is not 100% optimal.
This new implementation makes API calls not blocker since they are now encapsulated in their own go-routines.
> Fix QPS in non-optimal scenarios

- cmd/kube-burner/kube-burner.go
- cmd/kube-burner/ocp.go
- docs/cli.md
- pkg/burner/create.go
- pkg/burner/job.go
- pkg/burner/waiters.go
- pkg/indexers/factory.go
- pkg/prometheus/prometheus.go
- pkg/workloads/helpers.go
- test/run-ocp.sh
Add a --timeout flag to kube-burner so we can exit the benchmark after a preconfigured timeout.
This timeout is 2h by default, so we shall configure it accordingly in each test.
> Benchmark timeout flag

- pkg/burner/job.go
- pkg/prometheus/prometheus.go
For some reason there was two QueryRange statements, this was duplicating the prometheus query time 🤦🏽‍♂️ 
> Remove duplicated QueryRange

- cmd/kube-burner/ocp-config/cluster-density/np-allow-from-clients.yml
- cmd/kube-burner/ocp-config/cluster-density/np-allow-from-ingress.yml
- pkg/burner/create.go
- pkg/burner/job.go
- pkg/workloads/cluster-density.go
Improve churning code and increase churning delay
The default churning delay of 30s is very short, the cluster-density workload on this repo is more complex in terms of networking requirements, and needs a higher value (2 mins) to prevent excessive SDN delays.
> Churning improvements

- cmd/kube-burner/kube-burner.go
- cmd/kube-burner/ocp-config/cluster-density/cluster-density.yml
- docs/cli.md
- pkg/workloads/cluster-density.go
- test/run-ocp.sh
Add flag to opt-out network policies from the cluster-density workload
Pass the `--network-policies=false` argument to disable them
And increase default timeout to 4h
> Cluster-density network-policies flag and increase default timeout

- cmd/kube-burner/kube-burner.go
Adding -n flag to kube-burner init command as its familiar with kubectl flags
Signed-off-by: Chinmay Khare <chinmaykhare4992@gmail.com>
> Adding -n flag to kube-burner init command

- pkg/measurements/pod_latency.go
Some issues have recently popped up with respect to the way kube-burner calculates latencies of the pod phases.
The original implementation used the current timestamp when the pod was updated and detected by the Watcher, it turns out that this watcher is not 100% precise and can lead into delays when the load is high.
Using the LastTransitionTime field of the pod condition fixes the issue, however it comes with several trade-offs, most remarkable one is that:
- This field is provided in seconds, hence we'll loose the microsecond granularity when calculating the different latencies.
- Fixes: #237
> Use LastTransitionTime field in pod latency measurement

- pkg/burner/create.go
- pkg/burner/job.go
- pkg/burner/waiters.go
Given that the wait functions use a rate mechanism uses QPSx2 goroutines/s it's possible to observe client-side throttling since #goroutines > QPS like the below
```
I0123 17:27:24.771852 1651939 request.go:682] Waited for 2.996191263s due to client-side throttling, not priority and fairness, request: GET:https://198.18.10.132:6443/apis/apps/v1/namespaces/cluster-density-181/deployments
```
We need to create a new clientSet with higher QPS (actually x2) to be used by the wait functions to prevent it:
> ClientSet for wait functions

- cmd/kube-burner/ocp-config/alerts.yml
Reporting firing prometheus critical alerts can add a great value to the alerting system
> Report prometheus critical alerts

- pkg/burner/job.go
- pkg/measurements/metrics/metrics.go
- pkg/measurements/pod_latency.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- Add JobConfig metadata to all metric data
To Do :
- Add Extra metadata to all metric data from ocp wrapper
Note: Ignore JobConfig.Objects
Addresses some of https://github.com/cloud-bulldozer/kube-burner/issues/250
> Add additional metadata to metrics

- cmd/kube-burner/kube-burner.go
- cmd/kube-burner/ocp-config/node-density-cni/curl-deployment.yml
- pkg/burner/create.go
- pkg/burner/job.go
- pkg/burner/namespaces.go
- pkg/burner/pre_load.go
- pkg/burner/utils.go
- test/run-ocp.sh
With the old implementation, when a job times out the created namespaces are not garbage collected.
> Delete namespaces with timeout

- cmd/kube-burner/kube-burner.go
- cmd/kube-burner/ocp.go
- docs/cli.md
- log/log.go
- pkg/burner/job.go
- pkg/burner/metadata.go
- pkg/config/types.go
- pkg/measurements/factory.go
- pkg/measurements/metrics/metrics.go
- pkg/measurements/pod_latency.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- pkg/util/userMetadata.go
- pkg/workloads/helpers.go
- test/run-ocp.sh
- test/user-metadata.yml
Add clusterMetadata collected by the OCP wrapper to each indexed document. Also adds the flag --user-metadata to the ocp wrapper, index and init entrypoints.
Fixes: https://github.com/cloud-bulldozer/kube-burner/issues/250
> Add OCP metadata to each document

- pkg/burner/create.go
- pkg/burner/namespaces.go
- pkg/measurements/pod_latency.go
Use factory.jobConfig value rather than reference before setting NamespaceLabels to nil. Also removing the "name" label from the created namespaces, I don't recall why is there, but it's not used anywhere.
- Fixes: https://github.com/cloud-bulldozer/kube-burner/issues/256
> Use value rather than reference

- cmd/kube-burner/ocp-config/cluster-density/deployment.yml
- cmd/kube-burner/ocp-config/node-density/node-density.yml
- examples/workloads/api-intensive/templates/deployment.yaml
- examples/workloads/api-intensive/templates/deployment_patch_add_pod_2.yaml
- examples/workloads/cluster-density/templates/deployment.yml
- examples/workloads/kubelet-density/kubelet-density.yml
According to this k8s announcement:
>Legacy k8s.gcr.io container image registry will be frozen in early April 2023
k8s.gcr.io image registry will be frozen from the 3rd of April 2023.
Images for Kubernetes 1.27 will not available in the k8s.gcr.io image registry.
Please read our [announcement](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/) for more details.
> Update deprecated pause container repository

- cmd/kube-burner/ocp-config/metrics-aggregated.yml
- cmd/kube-burner/ocp-config/metrics.yml
With every release we seem to be adding more metrics and as a result more timeseries, samples and datapoints per minute to prometheus. It would be beneficial to maintain this data for historical comparisons and RCAing prometheus issues.
> Add prometheus related metrics to ocp wrapper

- pkg/discovery/discovery.go
The old implementation could use the infra node types as worker node type
> Discard infra nodes

- pkg/burner/create.go
We were checking IsForbidden rather than IsUnauthorized. According to the client-go docs they have different meanings:
Forbidden:
```shell
// StatusReasonForbidden means the server can be reached and understood the request, but refuses
// to take any further action.  It is the result of the server being configured to deny access for some reason
// to the requested resource by the client.
// Details (optional):
//   "kind" string - the kind attribute of the forbidden resource
//                   on some operations may differ from the requested
//                   resource.
//   "id"   string - the identifier of the forbidden resource
// Status code 403
StatusReasonForbidden StatusReason = "Forbidden"
```
Unauthorized:
```shell
// StatusReasonUnauthorized means the server can be reached …
```
> Replace IsForbidden by IsUnauthorized

- pkg/discovery/types.go
- pkg/workloads/helpers.go
Thanks to this new logic we can discover the platform from rosa based clusters.
Rosa infrastructure object:
```yaml 
apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
annotations:
include.release.openshift.io/ibm-cloud-managed: "true"
include.release.openshift.io/self-managed-high-availability: "true"
include.release.openshift.io/single-node-developer: "true"
release.openshift.io/create-only: "true"
creationTimestamp: "2023-04-03T09:44:06Z"
generation: 2
labels:
hypershift.openshift.io/managed: "true"
name: cluster
ownerReferences:
- apiVersion: config.openshift.io/v1
kind: ClusterVersion
name: version
uid: 722304ba-e77a-46e7-bb5b-9a5ca3da644c
resourceVersion: "1169"
uid: 901329cb-5d69-4281-8943-9a6a7791dbc2
spec:
cloudConfig:
name: ""
platformSpec:
aws: {}
type: AWS …
```
> Improve platform discovery logic

- docs/ocp.md
- pkg/burner/namespaces.go
- pkg/burner/pre_load.go
- pkg/discovery/discovery.go
Fixes: #247
The workloads available from the OCP wrapper weren't documented. Also adding more information about the `clusterMetadata` document.
> Add missing OCP wrapper documentation

- cmd/kube-burner/ocp-config/node-density-heavy/postgres-deployment.yml
The OCP clusters we interact with, normally have permissions to pull this image.
This reverts commit ad40e053d0c6d2db3346bb6349869d11f3e90092.
- Fixes: #298
> Revert "Use unauthenticated postgres image (#276)"

- pkg/burner/create.go
- pkg/config/config.go
The default value of wait was false, removing confusing Objects field declaration and set it in the  Object UnmarshalYAML implementation
> Fix wait default

- .github/workflows/containers.yml
The current client-go version is not supported in golang 1.18
> Update golang version in containers workflow

- pkg/burner/create.go
- pkg/burner/job.go
Removing job duration log message from `create.go` and print rounded duration in seconds rather than seconds with decimals
Fixes: https://github.com/cloud-bulldozer/kube-burner/issues/312
> Remove incorrect job duration message

- pkg/burner/waiters.go
The wait logic has been updated to support globally scoped objects. 
I hit this problem while working with Crossplane XRDs which have a global scope. 
Fixes #337
> Enable waiting on global objects

- pkg/workloads/helpers.go
Fixing indexing issues when es-config is not passed in CLI for ocp
> fixing indexing issues when es-config is not passed in CLI for ocp

- cmd/kube-burner/ocp-config/node-density-cni/node-density-cni.yml
- cmd/kube-burner/ocp-config/node-density-heavy/node-density-heavy.yml
- docs/ocp.md
- docs/reference/configuration.md
... failures running node-density-heavy and node-density-cni @245ppn on clusters with more than 24 worker nodes.
> Default iterations per namespace for cni heavy

- cmd/kube-burner/ocp-config/node-density-cni/node-density-cni.yml
- cmd/kube-burner/ocp-config/node-density-heavy/node-density-heavy.yml
- pkg/workloads/node-density-cni.go
- pkg/workloads/node-density-heavy.go
This commit adds namespaced-iterations and iterations-per-namespace
cli options to configure namespacedIterations and iterationsPerNamespace
respectively for node-density-cni and node-density-heavy workloads
> Add iterations-per-namespace as cli option

- pkg/burner/pre_load.go
Currently kube-burner does deploy a demonset for each image in the preload step which will create `pods=number_of_worker_nodes` for each image. This approach uses only one single deamonset for the entire list of images as we only care about pulling them into our cluster rather then running them in the `preload` step.
- Closes #
Tested on my self managed cluster by verifying the events. Attaching the logs below.
```
^C[vchalla@vchalla ~]$ oc get events
LAST SEEN   TYPE      REASON             OBJECT                   MESSAGE
14s         Normal    Scheduled          pod/preload2jpmt-hwcqc   Successfully assigned preload-kube-burner/preload2jpmt-hwcqc to ip-10-0-192-233.us-west-2.compute.internal
14s         Normal    AddedInterface     pod/preload2jpmt-hwcqc   Add eth0 …
```
> Using only one deamonset to fetch all the preload images

- cmd/kube-burner/ocp-config/cluster-density-v2/build.yml
- docs/reference/configuration.md
- pkg/burner/pre_load.go
- pkg/config/types.go
Added a parameter to specify node selectors in the preload step. This provides us with the flexibility to fully run kube-burner in desired set of nodes.
- Closes # https://github.com/cloud-bulldozer/kube-burner/issues/288
Tested building a binary on my self managed cluster.
Added labels `app=test` to one of worker nodes.
```
ip-10-0-183-53.us-west-2.compute.internal    Ready    worker                 82d   v1.25.8+27e744f   app=test,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.4xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2b,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-0-183-53.us-west-2.compute.internal,kubernetes.io/os=linux,node-role.kubernetes.io/worke …
```
> Adding node selector labels for preload step

- go.sum
- pkg/burner/pre_load.go
Fixes #390
This PR improves pre_load.go to not wait if there are no iamges to preload.
- Closes #390
> Do not wait for preLoadPeriod if there are no images to pre-load

- cmd/kube-burner/ocp-config/node-density-heavy/node-density-heavy.yml
Removing waitWhenFinished global flag by default in node density heavy  config.
Removing `waitWhenFinished` by default in node-density-heavy that was set in this [PR](https://github.com/cloud-bulldozer/kube-burner/pull/378).
- Closes #
> Removing waitWhenFinished global flag by default in node density heavy

- docs/measurements.md
- docs/reference/configuration.md
- pkg/burner/create.go
- pkg/burner/job.go
- pkg/burner/utils.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/measurements/pod_latency.go
Modifying logic to uniquely identify the run specific resources, ignoring the rest while calculating latencies. And also handling negative cases for v2 latencies to be on safe side, which ideally shouldn't happen in most of the cases.
- Related Issue # https://github.com/cloud-bulldozer/kube-burner/issues/413
- Closes #
Tested on self-managed AWS cluster and made sure the resources are not being repeated in latency calculations.
Initial run: https://gist.github.com/vishnuchalla/17d969f94d4cd1c909e29b6438837265
Follow up run: https://gist.github.com/vishnuchalla/da565a4de189f7c8edd6bb4a65ddc4fa
> Fixing measurement for pod lantencies

- Makefile
This PR fixes the missing versioning information
```
Version: fix_me
Git Commit: 6e42248f1a20fc6e3670df8db904a8fe0d2d226a
Build Date: 2023-08-14-16:48:30
Go Version: go1.20.1
OS/Arch: darwin amd64
# ../kube-burner/bin/amd64/kube-burner help
Kube-burner 🔥
Tool aimed at stressing a kubernetes cluster by creating or deleting lots of objects.
Usage:
kube-burner [command]
Available Commands:
check-alerts Evaluate alerts for the given time range
completion   Generates completion scripts for bash shell
destroy      Destroy old namespaces labeled with the given UUID.
help         Help about any command
import       Import metrics tarball
index        Index kube-burner metrics
init         Launch benchmark
ocp          OpenShift wrapper
version      Print the version number of kube-burner
Flags: …
```
> Fix the missing versioning information

- pkg/burner/job.go
- pkg/burner/namespaces.go
- pkg/measurements/pod_latency.go
- pkg/measurements/vmi_latency.go
- Remove the `measurementStopFunctions` variable.
- Call `CleanupNonNamespacedResourcesUsingGVR` during cleanup stage rather than `CleanupNonNamespacedResources`
- Add locks to pod latency calculations, multi-job benchmarks are failing due a potential concurrent map access by the different goroutines
- Missing fields to VMI & VM latency calculation
- Closes #
> Cleanup and code optimizations

- cmd/kube-burner/kube-burner.go
- docs/ocp.md
- pkg/alerting/alert_manager.go
- pkg/burner/job.go
- pkg/burner/namespaces.go
- pkg/measurements/factory.go
- pkg/measurements/metrics/metrics.go
- pkg/measurements/metrics/watcher.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
- pkg/measurements/vmi_latency.go
- pkg/workloads/helpers.go
Improving error handling. The Run() function now returns an exception (error) on these conditions:
- Benchmark timeout
- Measurement failure, returned from measurements Stop() methods
- Object count verification error
This new logic simplifies the error logic making it more efficient and easy to read.
---
In addition, all the errors are concatenated in a single string. That string is added to a new "errors" field of the `clusterMetadata` document as follows:
```shell
$ ./bin/amd64/kube-burner ocp node-density --pods-per-node=65 --pod-ready-threshold=1s  --local-indexing                                                                                   
time="2023-08-17 12:22:58" level=info msg="File node-density.yml available in the current directory, using it" file="helpers.go:181" …
```
> Improve error handling and messaging

- cmd/kube-burner/kube-burner.go
- pkg/alerting/alert_manager.go
- pkg/config/config.go
- pkg/measurements/pod_latency.go
- pkg/workloads/helpers.go
- test/k8s/kube-burner-index-single-endpoint.yml
- test/test-k8s.bats
Config file is not required anymore to run `kube-burner index`
- Closes #384
> Remove config File flag from index subcommand

- pkg/config/config.go
- test/test-ocp.bats
This PR creates a unique folder appended with the UUID, when used for local indexing. If the 'metricsDirectory' field is not populated, a folder of the type collected-metrics-UUID gets created. This PR addresses issue #402 
- Closes #402
> Create unique folder for every local indexing job using uuid

- pkg/burner/job.go
- pkg/burner/patch.go
The preLoad stage should only be executed in creation jobs
- Closes #
> PreLoad images only in creation jobs

- cmd/kube-burner/ocp-config/crd-scale/crd-scale.yml
- cmd/kube-burner/ocp-config/crd-scale/example-crd.yml
- cmd/kube-burner/ocp.go
- examples/workloads/crd-scale/crd-scale.yml
- examples/workloads/crd-scale/templates/example-crd.yml
- pkg/workloads/crd-scale.go
- pkg/workloads/workloads.go
This commit adds a new crd-scale workload under the ocp wrapper and also an example config file to run it standalone with the kube-burner command.
- Closes #
> Add new CRD scale workload

- docs/measurements.md
- pkg/measurements/pod_latency.go
* Finalizing V2 logic for latencies and removing V1.
* Keeping V2 as it is accurate, consistent and supportive for future development practices.
* Adding audit functionality based on V2 as it proved to be reliable. Please take a look at the attached issue for more context. 
- Related Issue # https://github.com/cloud-bulldozer/kube-burner/issues/439
- Closes #
Tested on self managed cluster with below command
```
kube-burner ocp node-density-heavy --timeout 1h --metrics-endpoint ~/metrics-endpoints.yaml --pods-per-node=50 --log-level=trace 2>&1 --gc=true | tee -a kube-burner-$(date +"%F_%H-%M-%S")
```
Full logs: https://gist.github.com/vishnuchalla/85f670152ac46ac898779ec301459a1b
> Adding audit functionality on latencies

- cmd/kube-burner/kube-burner.go
We need to explicitly set the UUID in the config instance when using the index or check-alerts subcommands. UUID is actually set when parsing a configuration file, and that's not required anymore in these subcommands
- Closes #
> Set UUID in config in index and check-alerts subcommands

- cmd/kube-burner/ocp-config/metrics-aggregated.yml
- cmd/kube-burner/ocp-config/metrics-report.yml
- cmd/kube-burner/ocp-config/metrics.yml
Recently we have seen regression in pod ready latency because of changes in multus code. CPU & memory usage of multus daemon increased while addressing this latency issue which resulted in more PRs.
We got a explict request from OVN team to track multus daemon metrics.
> add multus metrics

- cmd/kube-burner/ocp-config/metrics-aggregated.yml
- cmd/kube-burner/ocp-config/metrics.yml
https://github.com/openshift/cluster-network-operator/pull/1983 adds a new namespace (`openshift-network-node-identity`) and we need to be able to see the memory and CPU utilization for pods inside it.
> Add memory and CPU utilization for pods in openshift-network-node-identity namespace

- cmd/kube-burner/kube-burner.go
As per our discussion offline https://redhat-internal.slack.com/archives/C05CDC19ZKJ/p1695741562501689, 
Reverting to our previous time format in logs.
```
"2006-01-02 15:04:05"
```
Tested on a local machine.
```
time="2023-09-26 12:12:06" level=info msg="👽 Initializing prometheus client with URL: https://prometheus-k8s-openshift-monitoring.apps.play-area.perfscale.devcluster.openshift.com" file="prometheus.go:45"
time="2023-09-26 12:12:07" level=info msg="🔥 Starting kube-burner (oldtimeformat@56e243a16053ac5c7998ecb01766c85dba35bd0d) with UUID 6da716de-43ad-4584-96c5-44fb3e00ffb0" file="job.go:97"
time="2023-09-26 12:12:07" level=info msg="📈 Registered measurement: podLatency" file="factory.go:84"
time="2023-09-26 12:12:07" level=debug msg="Preparing create job: node-density-heavy" …
```
> Reverting to older timestamp format in logs

- cmd/kube-burner/ocp-config/metrics-aggregated.yml
- cmd/kube-burner/ocp-config/metrics-report.yml
- cmd/kube-burner/ocp-config/metrics.yml
I have found a lot of value in comparing the raw cpu_seconds aggregated at the few levels added here.
We currently index and report on the irate of these raw CPU seconds, but by using the raw seconds, we can report on the true cost of each change/component/namespace. This is just the first application of this kind of comparison.
They are important to have in all metrics profiles to make a meaningful comparison. They should be lighter than other metrics since we aren't retaining all nodes individually.
> Add new metrics for cpu seconds

- cmd/kube-burner/ocp-config/pvc-density/pod.yml
- cmd/kube-burner/ocp-config/pvc-density/pvc-density.yml
- cmd/kube-burner/ocp-config/pvc-density/pvc.yml
- cmd/kube-burner/ocp-config/pvc-density/storageclass.yml
- cmd/kube-burner/ocp.go
- pkg/workloads/pvc-density.go
- pkg/workloads/workloads.go
- test/test-ocp.bats
Add an experiment that creates a lot of Pods with corresponding PVCs that supports the default dynamic storage provisioning in a computing environment.
[gist of kube-burner standard output log](https://gist.github.com/mfleader/433acdac8b888e5bddccf0d842e720c1)
This software experiment would be aided by something like a PVC or PV latency calculation, similar to the pod latency calculation.
- Related Issue #427 
- Closes #427
> PVC Density/Stress

- pkg/prometheus/types.go
- pkg/util/metrics/metrics.go
- pkg/workloads/index.go
We weren't appending jobName to the metrics since https://github.com/cloud-bulldozer/kube-burner/pull/484
The uuid wasn't being set correctly in the index ocp subcommand 
- Closes #
> Fix index subcommands to append jobName and uuid

- cmd/kube-burner/ocp-config/alerts.yml
- pkg/alerting/alert_manager.go
Bumping detected in-cluster Prometheus alerts severity to error. kube-burner will return 1 in case of running into at least one of these alerts.
The rule kube-burner evaluates is
```
ALERTS{severity="critical", alertstate="firing"} > 0
```
which just tracks critical alerts in firing state, we could consider tracking alerts in error state as well, but maybe that would be too noisy
cc: @paigerube14  @svetsa-rh
- Closes #
> Bump prometheus alerts severity to error

- cmd/kube-burner/kube-burner.go
- docs/ocp.md
- docs/reference/configuration.md
- pkg/burner/job.go
- pkg/config/types.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- pkg/util/metrics/metrics.go
- pkg/util/metrics/tarball.go
- pkg/util/metrics/types.go
- pkg/util/metrics/utils.go
- pkg/workloads/helpers.go
- pkg/workloads/index.go
Simplifying the indexing logic, specially in util/metrics/metrics.go. `ScraperConfig` has now fewer fields, `actionIndex` is not required anymore, and standalone `index` subcommands take care of calling ScrapeJobsMetrics() by themselves rather than calling a function for everything like ProcessMetricsScraperConfig)() was
Also getting rid of these stale configuration parameters.
- prometheusUrl
- bearerToken
- metricsProfile
- metricsEndpoint
These config parameters are not being used and they increase the complexity the code quite a bit (they were added because it request of the arcaflow team, however they are not using them either)
--- 
Adding tarball creation support to `ocp index` and prevent indexing benchmark metadata in this subcommand, as its not actually required here.
#498 has …
> Simplifying metrics configuration logic

- pkg/burner/create.go
- pkg/burner/job.go
- pkg/burner/waiters.go
This PR tries to fix some race conditions on the "wait" logic that lead to observe a high amount of client-side throttling.
This client-side throttling can happen because originally kube-burner was creating a new goroutine for each object found in the job. That's to say, in a job with 5 objects, kube-burner can create up to 5 goroutines running in parallel , the problem with this approach is that the each one of these goroutines is spawned from another goroutine, which is limited to QPSx2. So in a worse case scenario with QPS/Burst=20/20 and 5 objects in a job we could see up to 20x2x5 = 200 requests in parallel which is way larger than the configured ClientSet rate limiter (QPSx2=40).
The new approach stops using children goroutines for the objects in a job, each namespace/iteration has …
> Fixing client-side throttling in wait stage

- cmd/kube-burner/ocp-config/networkpolicy-matchexpressions/networkpolicy-matchexpressions.yml
- cmd/kube-burner/ocp-config/networkpolicy-matchlabels/networkpolicy-matchlabels.yml
- cmd/kube-burner/ocp-config/networkpolicy-multitenant/networkpolicy-multitenant.yml
- cmd/kube-burner/ocp-config/pvc-density/pvc-density.yml
- docs/reference/configuration.md
- pkg/burner/job.go
- pkg/config/types.go
- pkg/measurements/pod_latency.go
- pkg/prometheus/prometheus.go
Ability to skip indexing on certain jobs, useful to prevent capturing datapoints from setup-up jobs
@mohit-sheth I've taken the liberty of adding this flag to the networkPolicy workloads, wdyt?
@josecastillolema I think this might be useful for web-burner as there're some set-up steps in the jobs you probably don't need to capture
- Closes #
> skipIndexing feature

- cmd/kube-burner/ocp-config/cluster-density-ms/deployment.yml
- cmd/kube-burner/ocp-config/cluster-density-ms/service.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/deployment-client.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/deployment-server.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/np-allow-from-clients.yml
- cmd/kube-burner/ocp-config/cluster-density-v2/service.yml
- cmd/kube-burner/ocp-config/cluster-density/deployment.yml
- cmd/kube-burner/ocp-config/cluster-density/service.yml
- cmd/kube-burner/ocp-config/node-density-cni/curl-deployment.yml
- cmd/kube-burner/ocp-config/node-density-cni/webserver-deployment.yml
- cmd/kube-burner/ocp-config/node-density-heavy/app-deployment.yml
- cmd/kube-burner/ocp-config/node-density-heavy/postgres-deployment.yml
- cmd/kube-burner/ocp-config/node-density/pod.yml
Implementing topology spread constraints in OCP workloads to help in evenly pod distribution 
Not patched:
```shell
$ ./bin/amd64/kube-burner ocp node-density-heavy --pods-per-node=100
<truncated>
$ kubectl get pods -n node-density-heavy-0 --field-selector=status.phase=Running -o go-template --template='{{range .items}}{{.spec.nodeName}}{{"\n"}}{{end}}'  | awk '{nodes[$1]++ }END{ for (n in nodes) print n": "nodes[n]}'
ip-10-0-133-30.us-west-2.compute.internal: 26
ip-10-0-173-62.us-west-2.compute.internal: 13
ip-10-0-217-162.us-west-2.compute.internal: 75
``` 
Patched:
```shell
$ ./bin/amd64/kube-burner ocp node-density-heavy --pods-per-node=100
<truncated>
$ kubectl get pods -n node-density-heavy-0 --field-selector=status.phase=Running -o go-template --template='{{range …
```
> Implementing topology spread constraints

- cmd/kube-burner/ocp-config/cluster-density-v2/build.yml
- cmd/kube-burner/ocp-config/cluster-density/build.yml
- examples/workloads/cluster-density/templates/build.yml
Build pods created by cluster density workloads actually use more like 70m CPU at peak. Adjusting this CPU request accordingly will help distribute the builds more evenly across the cluster. Unevenly distributed builds are a leading factor of higher pod latencies.
> Set more accurate 70m cpu request on cluster-density builds for better scheduling

- cmd/kube-burner/kube-burner.go
- cmd/kube-burner/ocp.go
- docs/cli.md
- docs/measurements.md
- pkg/config/config.go
- pkg/measurements/factory.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
- pkg/measurements/vmi_latency.go
- pkg/workloads/index.go
Introduced `measure` sub command to collection measurements in past.
- Related Issue # https://github.com/cloud-bulldozer/kube-burner/issues/138
- Closes # https://github.com/cloud-bulldozer/kube-burner/issues/138
Tested in local environment. Example config:
```
---
global:
indexerConfig:
esServers: ["{{.ES_SERVER}}"]
insecureSkipVerify: true
defaultIndex: {{.ES_INDEX}}
type: elastic
measurements:
- name: podLatency
thresholds:
- conditionType: Ready
metric: P99
threshold: 25s
```
Command to trigger:
```
kube-burner measure --uuid=vchalla --namespaces=cluster-density-v2-0,cluster-density-v2-1,cluster-density-v2-2,cluster-density-v2-3,cluster-density-v2-4 --labels=kube-burner-job=cluster-density-v2 
time="2023-11-12 21:22:09" level=info msg="📁 Creating indexer: elastic" …
```
> Measure sub command to collect measurements in past

- docs/reference/configuration.md
- go.mod
- go.sum
- pkg/burner/job.go
- pkg/config/types.go
- pkg/util/template.go
Create network-policy scale testing framework and 2 profiles for
openshift and ovn-kubernetes.
kube-burner modification: add ShutdownCondition to jobConfig. This
allows to set up a command that should exit before the workload
can be deleted. It is used by the network policy workload, since network
policy doesn't have a status, and extra means to track when the config
is applied are needed.
Add Binomial, IndexToCombination and GetSubnet24 functions for
templating, since they are needed to generate complex network policy
configs.
- Closes #
- [?] If it is a core feature, I have added thorough tests.
> Add network-policy workload

- pkg/burner/create.go
Make a per-goroutine copy of the `label` map to avoid concurrent read/writes to it.
- Closes #534
> Fix unsafe access to labels map to avoid a panic

- docs/reference/configuration.md
- pkg/config/config.go
In very large clusters or with large scale tests (100,000 plus pods) requests can take more than 15 seconds to list all objects. Bump the timeout to accommodate lots of objects.
> config: bump RequestTimeout to 60s by default

- test/helpers.bash
Sometimes metric documents are not immediately searchable, let's give them an extra time
```shell
time="2024-01-04 01:30:13" level=info msg="Indexing [2] documents from metric prometheusBuildInfo" file="utils.go:59"
time="2024-01-04 01:30:13" level=info msg="Indexing finished in 81ms: created=2" file="utils.go:64"
time="2024-01-04 01:30:13" level=info msg="Indexing [4] documents from metric prometheusRSS" file="utils.go:59"
time="2024-01-04 01:30:14" level=info msg="Indexing finished in 122ms: created=4" file="utils.go:64"
time="2024-01-04 01:30:14" level=info msg="Indexing [1] documents from metric top2PrometheusCPU-start" file="utils.go:59"
time="2024-01-04 01:30:14" level=info msg="Indexing finished in 41ms: created=1" file="utils.go:64"
time="2024-01-04 01:30:14" level=info …
```
> Add sleep before checking metrics in OS/ES

- docs/reference/configuration.md
- pkg/burner/create.go
- pkg/config/types.go
In certain cases on creating cluster wide resources like clusterroles, operator spec CRDs, network spec, they would not have to run for every iteration although it is idempotent, this additional option let us attempt just once during the  iteration within a job. 
We have many of such scenarios with ICNI implementaion like serviceaccount, SRIOV specs, ICNI CRDs are required to run only once within a job.
example object, when jobIteration is > 1
```
- objectTemplate: serviceaccount.yml
replicas: 1
runOnce: true
- objectTemplate: pod.yml
replicas: 1
```
- Closes #
> option to create an object only once in multi-iteration jobs

- pkg/burner/job.go
- pkg/burner/metadata.go
With the previous implementation, job's summary indexing was skipped when a prometheus endpoint wasn't specified, we should index this document whenever indexing is enabled.
- Closes #
> Index job summary regardless prometheus endpoint is set or not

- cmd/kube-burner/kube-burner.go
- pkg/burner/job.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- pkg/util/metrics/metrics.go
- pkg/util/metrics/utils.go
- pkg/workloads/helpers.go
- pkg/workloads/index.go
Passing a pointer to the indexer to the PrometheuClient saves some lines, reduces complexity and will enable kube-burner to have a different indexer in each PrometheusClient in the future.
- Closes #
> Pass the indexer instance to NewPrometheusClient

- cmd/kube-burner/kube-burner.go
- cmd/kube-burner/ocp.go
- go.mod
- go.sum
- pkg/config/config.go
`satori/uuid` repo is dead and has different problems as shown in https://github.com/satori/go.uuid/issues/84
Although a fork exists, IMO Google's module is simpler, even if the `NewString` function can be bit confusing as doesn't reference UUID V4 in the name as satori's and other modules do.
> Switch to Google's uuid module

- cmd/kube-burner/kube-burner.go
- docs/reference/configuration.md
- pkg/burner/create.go
- pkg/burner/namespaces.go
- pkg/burner/pre_load.go
- pkg/config/types.go
With this you can add [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) to namespaces that are created by kube-burner. 
Some of the features like ACL logging are enabled by the annotations field, this helps us exposing this field
> add annotations support to namespaces that are created

- docs/index.md
- docs/reference/configuration.md
- pkg/burner/job.go
- pkg/burner/read.go
- pkg/config/config.go
- pkg/config/types.go
- test/k8s/kube-burner-read.yml
- test/test-k8s.bats
Attempt to address https://github.com/kube-burner/kube-burner/issues/575
Adds new `jobType: read` which can be used to simulate load of GET requests 
- Closes #
> [WIP] Implement read jobType to simulate load with GET requests

- .github/workflows/test-k8s.yml
The current bats install action is deprecated, replacing it by the official one. 
- Closes #
> Replace deprecated bats-action

- pkg/workloads/helpers.go
- pkg/workloads/types.go
The Indexer field from the workloads.Config  struct, this field is not necessary, we should use the value of the configuration file rather than relying on a field set on this structure.
This PR is part of a bug fix that happens when using a configuration file in the ocp-wrapper with an indexer in the configuration file and a workload is executed w/o passing es-server/es-index/local-indexing
- Related Issue https://github.com/kube-burner/kube-burner-ocp/issues/7
> Remove indexer from workload config

- cmd/kube-burner/kube-burner.go
- docs/measurements.md
- pkg/burner/create.go
- pkg/burner/job.go
- pkg/measurements/factory.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
- pkg/measurements/service_latency.go
- pkg/measurements/types/types.go
- pkg/measurements/vmi_latency.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- pkg/util/namespaces.go
Indexing measurement metrics is not a blocking operation anymore, subsequent jobs don't have to wait for the metrics to be indexed, some changes were required to prevent race conditions when we restart measurements and the metrics hasn't been indexed yet.
- Closes #589
> Make measurement indexing not a blocking operation

- cmd/kube-burner/kube-burner.go
- docs/cli.md
- docs/reference/configuration.md
- examples/workloads/cluster-density/cluster-density.yml
- pkg/config/types.go
- pkg/util/cluster_health.go
- test/test-k8s.bats
The health check is designed to assess the condition of nodes and cluster operators within a Kubernetes cluster. In vanilla Kubernetes, the evaluation is focused on the node status. However, for OpenShift (OCP), the health check encompasses both node status and the status of cluster operators.
Initiating the health check can be achieved by either configuring the global settings with ```clusterHealth: true``` during workload execution or by directly invoking the command ```kube-burner health-check```.
output 1
```
sboyapal cluster-density (healthcheck) >> kube-burner health-check
time="2024-01-31 17:02:37" level=info msg="Checking for Cluster Health" file="kube-burner.go:182"
time="2024-01-31 17:02:39" level=info msg="Cluster is healthy." file="kube-burner.go:187"
time="2024-01-31 …
```
> Cluster health check

- pkg/prometheus/prometheus.go
- pkg/util/metrics/metrics.go
- pkg/workloads/helpers.go
Fixing leftover bug through:https://github.com/kube-burner/kube-burner/pull/602, which was not publishing clusterMetadata due to nil value being populated in indexer variable.
Tested integrating with OCP wrapper. My own release verified in this PR: https://github.com/kube-burner/kube-burner-ocp/pull/33/files
> Bug fix for OCP clustermetadata indexing

- pkg/measurements/metrics/metrics.go
- pkg/measurements/pod_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/vmi_latency.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
Keeping `jobConfig` only in the `jobSummary` document and removing from rest of the metrics. This field is redundant and is not used anywhere including our grafana dashboards.
Verified that there wouldn't be any impact in all our grafana dashboards as the existing queries can get required UUIDs from the `jobConfig` and `metadata` fields present in the `jobSummary` document which should be sufficient enough.
Analysis proving the above statement: https://gist.github.com/vishnuchalla/33ec9ef9861c458cc3378d3d92eaca50
Also one more advantage of doing this is, its going to reduce around `40%` of space occupied by kube-burner elastic search indices. Example
```
[vchalla@vchalla-thinkpadp1gen2 collected-metrics-vchalla-testmar30regular]$ du -sh
9.0M	
```
```
[vchalla@vchalla-thinkpadp1gen2 …
```
> Removing jobConfig from the metrics

- pkg/util/metrics/metrics.go
We were appending a PrometheusClient to the clients slice in all cases even when that prometheus client was going to be used to scrape alerts, this clients in this slice are used to scrape metrics and no other client there should be added.
- Closes #616
> Only append prometheus client to slice when it has a metrics profile

- docs/measurements.md
- docs/observability/indexing.md
- docs/observability/metrics.md
- docs/reference/configuration.md
- examples/workloads/kubelet-density-heavy/kubelet-density-heavy.yml
- pkg/burner/waiters.go
- test/helpers.bash
The `waitForPod` implementation was incorrect and follows a different logic compared to the `waitForDeployments` function.
In the original implementation, this logic waits for all pods in the specified namespace to have status.phase as Running. Which according to the docs means
>- `"Running"` means the pod has been bound to a node and all of the containers have been started. At least one container is still running or is in the process of being restarted.
Meaning that the status phase of the pod can be `Running`, w/o passing any probe.
This behaviour is different in Pods handled by a controller such as Deployment or DaemonSet, in which kube-burner uses the ReadyReplicas/NumberReady status fields, and these fields depend on the Ready condition of the child pods, this condition is marked as …
> Improve pod waiter

- pkg/burner/job.go
- pkg/config/config.go
+ Do not set default `job.MaxWaitTimeout` in `UnmarshalYAML`
+ Override `job.MaxWaitTimeout` only if it is empty
- Closes #618
> Don't override maxWaitTimeout in job spec

- pkg/config/config.go
Skip `validation.IsDNS1123Subdomain` when job.Namespace  is empty.
- Closes #628
> validate job.Namespace when it's non empty.

- pkg/util/namespaces.go
+ `resourceInterface.Delete` is a non-blocked function.
+ If run `resourceInterface.Delete` in a goroutine, the `resourceInterface.Delete` haven't had a chance to run before `kube-burner` exit.
- Closes #630
> Directly delete non-namespaced resource

- cmd/kube-burner/kube-burner.go
- pkg/alerting/alert_manager.go
- pkg/util/metrics/metrics.go
- test/k8s/alerts.yml
- test/test-k8s.bats
check-alerts was broken due to a nil pointer in indexer
```shell
$ ~/labs/kube-burner/bin/amd64/kube-burner check-alerts -a up.yml -u http://localhost:9090                                                         16:18:54 [118/1437]
time="2024-04-22 16:16:04" level=info msg="👽 Initializing prometheus client with URL: http://localhost:9090" file="prometheus.go:47"
panic: runtime error: invalid memory address or nil pointer dereference                                                
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b4d890]                                                                                                                                                                       
goroutine 1 [running]: …
```
> Fixing check-alerts command and add test case

- pkg/burner/waiters.go
`waitForPVC` does not work, kube-burner will not wait pvc to be `Bound` before deleting pvc.
`PersistentVolumeClaim` does not support field-selector `status.phase`
```
[root@master-1 ~]# kubectl get pvc --field-selector status.phase!=Bound
Error from server (BadRequest): Unable to find "/v1, Resource=persistentvolumeclaims" that match label selector "", field selector "status.phase!=Bound": "status.phase" is not a known field selector: only "metadata.name", "metadata.namespace"
``` 
Only `Pod` and `Namespace` support `status.phase` Field.
https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#list-of-supported-fields
- Closes #
> Remove unsupported FieldSelector in waitForPVC

- pkg/burner/create.go
- pkg/burner/patch.go
- pkg/burner/pre_load.go
- pkg/burner/utils.go
error log when  error decoding YAML,finding error is difficult.
`"Error decoding YAML: yaml: line 11: could not find expected ':'" file="utils.go:75"`
adding a file name makes it easy
`"Error decoding YAML file (templates/xxx.yaml): yaml: line 11: could not find expected ':'" file="utils.go:75"`
- Closes #
> Add fileName when Error decoding YAML

- cmd/kube-burner/kube-burner.go
- test/test-k8s.bats
Support for multiple metric profiles in the index sub-command.
Added a CI test and verified it locally.
```
kube-burner index --uuid="${UUID}" -u http://localhost:9090 -m "metrics-profile.yaml,metrics-profile.yaml" --tarball-name=metrics.tgz
```
> Adding support for multiple metric profiles

- pkg/prometheus/prometheus.go
- pkg/workloads/helpers.go
Adding fallback logic to ready metric profiles properly when specified from a metrics-endpoint file. Previous logic used to append prefix "config" which was leading to errors.
Tested and verified in local integrating with ocp wrapper.
```
[vchalla@vchalla-thinkpadp1gen2 kube-burner-ocp]$ kube-burner-ocp cluster-density-v2 --log-level=info --qps=20 --burst=20 --gc=true --uuid 78cf9e75-1d7a-407f-98cc-a389e0ed4852 --gc-metrics=true --profile-type=reporting --gc-metrics=true --profile-type=reporting --iterations=1 --churn=true --es-server='https://ocp-qe:Perfscale24!@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com' --es-index=ripsaw-kube-burner --metrics-endpoint=metrics-endpoint.yml --log-level=debug
time="2024-05-10 16:00:44" level=info …
```
> fallback logic while reading metric profiles

- pkg/util/template.go
RFE https://github.com/kube-burner/kube-burner-ocp/issues/32
GetIPAddress renders a string with IP addresses for the object template from the list of input addresses based on iteration number and number of addresses requested per object
> get addresses for job iteration object

- docs/cli.md
> Removing configmap and namespace references from CLI docs

- docs/observability/metrics.md
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- test/k8s/metrics-profile.yaml
- test/test-k8s.bats
We normally don't need to capture the start of the metric
- Closes #603
> Capturing start is optional in instant metrics

- cmd/kube-burner/kube-burner.go
- docs/observability/indexing.md
- pkg/alerting/alert_manager.go
- pkg/burner/job.go
- pkg/burner/metadata.go
- pkg/workloads/helpers.go
- pkg/workloads/types.go
- test/test-k8s.bats
Update the format of the `jobSummary` document, to include the fields:
- passed: This field indicates if the job passed of not. To fail means that any of these conditions were true:
- An alert of error severity was fired
- Pod latency thresholds not met
- Object verification failed
- executionErrors: Details the error reason
One of the goals of this new approach is to get rid of the document `benchmarkMetadata` generated by `kube-burner-ocp` and consolidate into a single one.
- Closes #
> Enrich jobSummary

- pkg/measurements/vmi_latency.go
Removing unnecessary incompatibility check for the VMI latency measurement in delete jobs. The measurement can be running while a VM/VMI is deleted w/o issues, as it just handles the latency of new created VM/VMIs
This check was leading into issues, the logic wasn't 100% correct as it was trying to stop it even when it hasn't been previously started.
- Closes #658
> Remove incompatibility check

- docs/observability/indexing.md
- go.mod
- go.sum
- pkg/workloads/helpers.go
After merging https://github.com/kube-burner/kube-burner/pull/620, the cluster's metadata wasn't being added to the `jobSummary` document, this change helps to add **all** fields from cluster metadata to **all** documents generated (including jobSummary), it simplifies the overall logic by not having to select a subset of fields to add in the metrics.
> Note: The metadata fields are added when using the plugin helpers functions 
- Related Issue #620
- Closes #
> Add cluster metadata information to all documents when using plugin helpers

- pkg/workloads/helpers.go
It prevents having to initialize it externally and thus potential nil pointer exceptions.
- Closes #
> Initialize MetricsMetadata map

- pkg/prometheus/prometheus.go
- pkg/util/metrics/metrics.go
Removing metadata when it is empty to have more cleaner metrics.
Tested in local and verified
```
{
"timestamp": "2024-07-07T19:27:14.434Z",
"labels": {
"container": "lightspeed-service-api",
"namespace": "openshift-lightspeed",
"node": "ip-10-0-78-217.us-west-2.compute.internal",
"pod": "lightspeed-app-server-6c695f7995-ztp4q"
},
"value": 0.11032656977364322,
"uuid": "158de0a0-7fd0-4879-8798-ae1ddcb8b5c2",
"query": "(sum(irate(container_cpu_usage_seconds_total{name!=\"\",container!~\"POD|\",namespace=~\"openshift-lightspeed\"}[2m]) * 100) by (container, pod, namespace, node)) > 0",
"metricName": "containerCPU"
}
```
> Handling empty metadata cases to be handled in metrics.

- docs/reference/configuration.md
- pkg/burner/patch.go
- pkg/burner/read.go
- pkg/burner/waiters.go
- pkg/config/types.go
Enhancing wait options to work with labels, custom conditions also for the read jobs.
* Scans only objects with specified labels.
* Works with custom condition if specified.
* Works with nested resources of an application deployment.
* Also works with 
- Related Issue # https://github.com/kube-burner/kube-burner/issues/653
Went through the CI tests.
Tested and verified in local with a config change
```
- objectTemplate: app-deployment.yml
replicas: 1
inputVars:
probesPeriod: {{.PROBES_PERIOD}}
waitOptions:
labelSelector: {kube-burner-uuid: abcd}
forCondition: Available
```
> Enhancing waitoptions to work with lablels, custom conditions & read jobs

- pkg/measurements/pod_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/vmi_latency.go
Using sycn.Map in all our measurement calculations so that we don't have to worry about thread safety as it is offered in-built. With this change we get rid of all the mutex locks that we have. Also this will help us stay away from concurrent read/write issues in the metrics maps.
- Related Issue # https://github.com/kube-burner/kube-burner/issues/650
Tested in local integrating with ocp wrapper.
```
time="2024-07-17 15:48:04" level=info msg="Stopping measurement: podLatency" file="factory.go:125"
time="2024-07-17 15:48:04" level=info msg="Evaluating latency thresholds" file="metrics.go:46"
time="2024-07-17 15:48:04" level=info msg="node-density-heavy: PodScheduled 50th: 0 99th: 1000 max: 1000 avg: 18" file="pod_latency.go:236"
time="2024-07-17 15:48:04" level=info …
```
> Using sync.Map for thread safety to calculate measurements

- pkg/burner/job.go
- pkg/burner/metadata.go
Capturing metrics even in timeout cases. Also populating job status and execution errors appropriately.
- Related Issue # https://github.com/kube-burner/kube-burner/issues/626
> indexing metrics even in timeout cases

- docs/cli.md
Kube-burner docs fix. under init reference chapter URL  is not working. https://kube-burner.github.io/kube-burner/latest/cli/#init
- Closes #
> Docs update in reference chapter url under init.

- cmd/kube-burner/kube-burner.go
- docs/cli.md
- docs/observability/indexing.md
- pkg/burner/metadata.go
- pkg/measurements/pod_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/vmi_latency.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- pkg/util/metrics/metrics.go
- pkg/workloads/helpers.go
- pkg/workloads/types.go
With this PR, cluster's metadata is no longer added to all documents except `jobSummary`. This helps to reduce the size of the generated documents.
- Closes #
> Removing metadata from documents except jobSummary

- pkg/burner/job.go
Let's prevent calling measurements.Index() when the indexer list is empty
- Closes #
> Prevent indexing measurements when indexers list is empty

- .golangci.yml
- .pre-commit-config.yaml
- cmd/kube-burner/kube-burner.go
- pkg/alerting/alert_manager.go
- pkg/burner/create.go
- pkg/burner/job.go
- pkg/burner/read.go
- pkg/burner/waiters.go
- pkg/measurements/service_latency.go
- pkg/util/template.go
- pkg/workloads/helpers.go
The previous hook wasn't working as expected as it was relying on this configuration https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml#L1-L8 `golangci-lint run --new-from-rev HEAD --fix`, the hook's command basically fixes linting errors when the current code is different from HEAD (so no action is taken when changes are committed), this is not what we actually need, we want to report and hang on linting errors caused by a PR.
Also fixing some pieces of code to meet linting.
- Closes #
> Fix golangci-lint precommit hook

- pkg/alerting/alert_manager.go
- pkg/burner/job.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
Prevent indexing `churnStartTimestamp` and `churnEndTimestamp` when churning is not enabled
- Closes #
> Skip churnStartTimestamp and churnEndTimestamp from jobSummary when churning is not on

- .github/workflows/test-k8s-ppc64le.yml
- Makefile
- test/helpers.bash
This PR adds workflow to test the kube-burner binary on the ppc64le architecture, as a part of CI/release testing.
A dedicated VM for the project is available, I can work with @krishvoor for the access and details for the broader team's usage.
- Closes #646
> Add workflows to test kube-burner on ppc64le

- pkg/measurements/pod_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/vmi_latency.go
The metricName of the vmi latency letrics wasn't correct (it was using podLatency as name), also logging the summary of the observed results similar to other measurements. 
- Closes #
> Rename vmi latency measurement metrics

- .github/workflows/ci-tests.yml
- kube-burner-virt.yml
- test/helpers.bash
- test/k8s/kind.yml
- test/k8s/kube-burner-virt.yml
- test/k8s/objectTemplates/kubevirt-cr.yaml
- test/k8s/objectTemplates/vm-ephemeral.yml
- test/test-k8s.bats
Adding kube-virt into the CI. This will help us deploy VMs and validate our code against them. Pre-requisite: https://github.com/kube-burner/kube-burner/pull/700
- Closes # https://issues.redhat.com/browse/PERFSCALE-3400?filter=-1
Tested and verified the lifecycle through fork github actions: https://github.com/vishnuchalla/kube-burner/actions/runs/10927130633/job/30332622126
> Adding kube-virt to the CI tests

- pkg/workloads/helpers.go
kube-burner-ocp workloads are using workload helpers for Run command. However this Run() has os.exit(), which is blocking kube-burner-ocp to run any PostRun() commands.
As we removed os.exit() here, kube-burner-ocp workloads explicitly need to define PostRun() with os.exit().
kube-burner-ocp PR https://github.com/kube-burner/kube-burner-ocp/pull/115 which adds PostRun() in all workloads
> Remove os.exit in Run

- pkg/util/url_reader.go
- test/test-k8s.bats
The current `ReadConfig` function attempts to read the `configFile` string as a URL. It falls back to treating it as a file path only if parsing the URL fails. This logic is causing the issue where absolute file paths pass the initial check. 
My suggested change uses `url.Parse` to check for a valid URL format. Instead of assuming any valid URI is a URL, it explicitly checks for the `http` or `https` schemes. Only if those schemes are present does it treat the `configFile` string as a URL.
- Closes #683
> [GH#683] fix: absolute file paths interpreted as urls

- docs/reference/configuration.md
- pkg/burner/patch.go
- pkg/config/types.go
- test/helpers.bash
- test/k8s/kube-burner-sequential-patch.yml
- test/k8s/objectTemplates/deployment_patch_label.yaml
- test/test-k8s.bats
Sequential execution runs all objects in a job iteration before reiterating
It allows delaying between objects and/or job iterations
Add PatchExecutionType for backward compatibility
- Closes #713
> Add support for sequential handling on Patch jobs and objects

- .github/workflows/test-k8s.yml
- Makefile
- docs/contributing/tests.md
- test/helpers.bash
- test/test-k8s.bats
The tests failed to run on a local Linux machine. To allow running it locally two main changes were required:
1. Run `opensearch` locally and instruct the tests to report to it
2. Run the tests with the locally built binary
In addition, instructions on running rootful Podman were added.
> Allow running the test suite on a local Linux machine

- docs/reference/configuration.md
- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/job.go
- pkg/burner/patch.go
- pkg/burner/read.go
- pkg/burner/utils.go
- pkg/config/types.go
- test/k8s/kube-burner-sequential-patch.yml
Rename executionMode to unlink from patch
Move runJob and its internals to utiles  and use in Read and Delete jobs
Add ObjectFinalizer in addition to ItemHandler
Set Job for Executor and make sure it is not accesses once it is passed to executor
Remove redundant labelSelector and patchType fields from object
> Reuse runJob for Delete and Read

- docs/contributing/tests.md
- test/helpers.bash
- test/test-k8s.bats
Allow running the tests with an existing cluster instead of running a dedicated one using Kind. This resolves cases in which users do not have root access in order to use rootless podman or if KVM is not supported (e.g. MacOS)
> Tests - allow running against an existing cluster

- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/executor.go
- pkg/burner/job.go
- pkg/burner/object.go
- pkg/burner/patch.go
- pkg/burner/pre_load.go
- pkg/burner/read.go
Consolidate the setup and creation of object and executor instances into a generic code.
For object, keep create with the old implantation as it is different from the rest
> Reuse Executor and object setup code

- docs/measurements/index.md
- pkg/measurements/pod_latency.go
- test/helpers.bash
Very interesting new pod condition, enabled by default as of k8s 1.29 (OCP 4.16)
More info at https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-has-network
We can look at it to establish a new KPI directly inherited from CNI performance
- Closes #
> New PodReadyToStartContainers condition to pod_latency measurement

- pkg/measurements/netpol_latency.go
- pkg/measurements/util/port_forward.go
On some environments, client port forwarding can use both ipv4 and ipv6 addresses for port forwarding. kube-burner has to consider this scenario as well while parsing the port forwarding output and fetch the local port.
- Closes #749
> fix localport in port forwarding

- cmd/kube-burner/kube-burner.go
- pkg/alerting/alert_manager.go
- pkg/burner/create.go
- pkg/burner/delete.go
- pkg/burner/executor.go
- pkg/burner/kubevirt.go
- pkg/burner/object.go
- pkg/burner/patch.go
- pkg/burner/read.go
- pkg/config/types.go
- pkg/measurements/factory.go
- pkg/measurements/netpol_latency.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/types.go
- pkg/util/metrics/metrics.go
- pkg/util/metrics/types.go
- pkg/util/metrics/utils.go
- pkg/util/url_reader.go
- pkg/workloads/helpers.go
- pkg/workloads/types.go
Create a single GetReader function for all sources
Adjust all Reader operations to use the new function
Adjust APIs where needed
Remove the redundant embedConfig flag from Prometheus and Alert Manager
Make the EmbedFS field a pointer to allow simple check
When using via `kube-burner-ocp` patch jobType could not read from the embedded file system.
> Consolidate file read to a single function

- docs/reference/configuration.md
- pkg/burner/executor.go
- pkg/burner/job.go
Add the RunID to the template param to allow marking sub-resources for metrics
> Template - pass the job run id to the template

- pkg/burner/job.go
- pkg/util/bash.go
Instead of calling `/bin/sh` on the script file, read the content of the file and run it from stdin. 
Note, this works only when all the script code is in a single file
Fail to execute shell scripts when using embedded file system
> Support running shell scripts from the embedded filesystem

- pkg/alerting/alert_manager.go
- pkg/prometheus/prometheus.go
- pkg/util/url_reader.go
Reading profiles from embedded was not working since https://github.com/kube-burner/kube-burner/pull/761
- Closes #
> Fix metric and alerting profile reads in embedded directories

- cmd/kube-burner/kube-burner.go
- docs/cli/index.md
- pkg/config/config.go
Add argument to the init command to allow missing keys in the configuration file.
> Init - Add CLI arg to allow missing keys

- cmd/kube-burner/kube-burner.go
- pkg/burner/job.go
- pkg/measurements/common.go
- pkg/measurements/factory.go
- pkg/measurements/netpol_latency.go
- pkg/measurements/node_latency.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
- pkg/measurements/service_latency.go
- pkg/measurements/vmi_latency.go
Create two layers of factories to allow handling of global and per job parameters
Use instances and their methods to manage measurements
Remove all runtime global variables from the measurements factory
Adjust the different implementations to the new scheme
Adjust the different users of measurements to the new scheme
- Closes #766
> Measurements - use new instances for each job to allow deferred indexing

- pkg/burner/utils.go
- pkg/config/config.go
To allow running the same test sequence with the same UUID, generate the RUNID every time the configuration spec is loaded and verify objects that were created under the specific runid
> Verify - limit the objects list to the ones created in the current run

- docs/measurements/index.md
- examples/workloads/deployment-pvc-move/deployment-pvc-move.yml
- pkg/measurements/common.go
- pkg/measurements/factory.go
- pkg/measurements/pvc_latency.go
- test/test-k8s.bats
Adding PVC latency to family of measurements.
Closes # https://github.com/kube-burner/kube-burner/issues/426
Tested and verified in local
```
time="2025-01-09 18:13:47" level=info msg="pvc-move: Bound 99th: 4544 max: 4544 avg: 4544" file="pvc_latency.go:206"
time="2025-01-09 18:13:47" level=info msg="pvc-move: Lost 99th: 0 max: 0 avg: 0" file="pvc_latency.go:206"
time="2025-01-09 18:13:47" level=info msg="pvc-move: Pending 99th: 93 max: 93 avg: 93" file="pvc_latency.go:206"
```
> Adding PVC latency to measurements

- examples/workloads/kubevirt-density/kubevirt-density.yml
Fix virt-launcher pod deletion selection, such that it only deletes kube-burner initiated virt-launcher pods. Else it attemps to delete all virt-launcher pods under all namespaces, a potential risk if this kube-burner example is ever executed in a production system.
- [ x] Bug fix
Limit the label selection on  [L34](https://github.com/kube-burner/kube-burner/blob/main/examples/workloads/kubevirt-density/kubevirt-density.yml#L34)  and [L92 ](https://github.com/kube-burner/kube-burner/blob/main/examples/workloads/kubevirt-density/kubevirt-density.yml#L92)  to virt launcher pods created by kubevirt-density job.
> Limit virt-launcher deletion to kube-burner pods

- .github/workflows/test-k8s.yml
The sem ver for the container image tag starts with `v`
> CI - Fix regex for container image sem_ver

- cmd/kube-burner/kube-burner.go
- pkg/config/config.go
- pkg/workloads/helpers.go
When using kube-burner as a package passing parameters as environment variables may be cumbersome. Instead, allow passing the values via a method parameter
> Allow passing additional variables when using as a package

- Makefile
- docs/contributing/tests.md
Allow contributors to run specific tests while still using the test-k8s rule
> Makefile - allow passing a filter to bats when running tests

- docs/reference/configuration.md
- pkg/burner/utils.go
- pkg/burner/waiters.go
- pkg/config/types.go
- test/k8s/kube-burner-virt-operations.yml
- New feature
- Bug fix
Add a new job parameter to wait between objects
In Sequential run check and wait at the object and at the job iteration level
Adjust testing
Add to doc
> Allow waiting for status between objects in the same job iteration

- pkg/burner/waiters.go
- Bug fix
Fix race condition in which the waiter checks for a field in the status that does not yet exist.
For example, waiting on a condition before there are any
> Waiters - do not fail if query jq failed

- .github/workflows/check-docs-links.yml
- pkg/burner/create.go
- pkg/burner/namespaces.go
Adding iteration churning. Churn workflow will now onwards automatically decide if to delete an entire namespace or just few iterations in case of single namespace workloads.
Closes # https://github.com/kube-burner/kube-burner/issues/673
Tested on a self-managed OCP cluser using node-density and verified the funtionality.
```
vchalla@vchalla-thinkpadp1gen2:~/myforks/kube-burner-ocp$ kube-burner-ocp node-density --pods-per-node=23
time="2025-01-10 18:12:41" level=info msg="❤️ Checking for Cluster Health" file="cluster_health.go:45"
time="2025-01-10 18:12:42" level=info msg="Cluster is Healthy" file="cluster_health.go:53"
time="2025-01-10 18:12:43" level=info msg="🔥 Starting kube-burner (main@36359f30301b7f68e59f1c729b020ce57028dbfa) with UUID d787cc75-c9f6-45c3-be2e-23e3f0ac9430" …
```
> Adding iterations churning

- pkg/burner/waiters.go
- Optimization
Since all items are fetched on each try, the log becomes too verbose. Change success to debug message
> Waiter - reduce verbosity on successful checks

- mkdocs.yml
The nav item was pointing to `wrappers/index` instead of `wrappers/wrappers` resulting in a broken link.
- Closes #816
> [GH#816] fix wrappers 404 in docs

- pkg/measurements/vmi_latency.go
- Bug fix
Filter the pod watcher for vmi latency to those marked as virt-launcher to avoid warning of unrelated pods
> VMI Latency - watch only for virt-launcher pods

- pkg/burner/utils.go
- test/k8s/kube-burner.yml
- test/k8s/objectTemplates/secret.yml
- Bug fix
When `runOnce` is set the number of created items is the number is in `replicas` without multiplying it be the number of iterations.
- Closes #821
> Expect items from a single iteration when RunOnce is set

- test/grafana/test-dashboard.json
- test/helpers.bash
- test/test-k8s.bats
- New feature
- CI
Adding a option to ship grafana dashboards in our CI.
Closes # https://github.com/kube-burner/kube-burner/issues/433
Tested in local using `DEPLOY_GRAFANA=true make test-k8s`
> Ship grafana dashboard in CI

- docs/reference/configuration.md
- pkg/burner/delete.go
- Bug fix
waitWhenFinished searches for resources while a delete job removes them. As a result, waitWhenFinished should never be used. Instead WaitForDeletion should be used
> Delete job - always set waitWhenFinished to false

- pkg/burner/job.go
- pkg/util/namespaces.go
- Bug fix
With this new logic, when garbage collection times out, execution is not aborted (so indexing won't be interrupted) and kube-burner's rc will be 2, as per documented rc for timeout cases.
- Closes #842
> Prevent aborting execution on garbage collection timeout

- cmd/kube-burner/kube-burner.go
- docs/measurements/index.md
- pkg/burner/job.go
- pkg/measurements/common.go
- pkg/measurements/datavolume_latency.go
- pkg/measurements/factory.go
- pkg/measurements/netpol_latency.go
- pkg/measurements/node_latency.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pprof.go
- pkg/measurements/pvc_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/snapshot_latency.go
- pkg/measurements/vmi_latency.go
- pkg/workloads/helpers.go
This enables kube-burner-ocp to define its own measurement functionality (example, network-policy-measurement.go, router-advertisement-measurement.go). This is required to avoid using openshift CRD in kube-burner measurements code.
To support reusability of the measurements package outside the core kube-burner project, I updated relevant structs, variables, interfaces, and functions to use exported identifiers (i.e., starting with capital letters). This makes them accessible from external packages like kube-burner-ocp, allowing the extension of measurement functionality while staying within Go's visibility rules.
Now kube-burner-ocp prepares measurementFactoryMap with the core measurements (like pod, service latency) and additional measurements which is defined in kube-burner-ocp (like …
> Refactored the measurements package to support external use

- .github/workflows/docs.yml
- Bug fix
- CI
Previous logic to fetch all the tags used to sort them in descending order lexicographically, which wasn't what we wanted in reality. So fixing that logic to fetch the logs and sort them solely based on creation times so that we fetch and keep only 3 latest version of them and delete the rest.
There have been failures in deploying docs in the past due to this issue.
Tested and verified these changes locally in a hacky way.
```
v1.15.1
v1.15.0
v1.14.3
v1.14.2
v1.14.1
v1.14.0
v1.13.0
v1.12.1
v1.12.0
v1.11.3
v1.11.2
v1.11.1
v1.11.0
v1.10.9
v1.10.8
v1.10.7
v1.10.6
v1.10.5
v1.10.4
v1.10.3
v1.10.1
v1.10.0
v1.9.8
v1.9.7
v1.9.5
v1.9.4
v1.9.3
v1.9.2
v1.9.1
v1.9.0
v1.8.1
v1.8.0
v1.7.13
v1.7.12
v1.7.11
v1.7.10
v1.7.9
v1.7.8
v1.7.7
v1.7.6
v1.7.5
v1.7.4
v1.7.3
v1.7.2 …
```
> Fix logic to sort tags based on creation date

- pkg/burner/conditions.go
- Bug fix
When kube-burner waits for Job completion, the JQ query would fail with `"cannot iterate over: null"` warnings when the Job's `status.conditions` field hasn't been populated yet by the Kubernetes controller.
This is a race condition between Job creation and status population that occurs during the initial phase of Job lifecycle. The warnings were harmless as the waiter would retry, but they created noise in the logs.
The fix updates the JQ query patterns to use the alternative operator (`//`) to provide an empty array default when conditions is `null`.
Component: conditions
- Closes #853
> fix(conditions): handle null conditions in JQ queries to prevent warnings

- cmd/kube-burner/kube-burner.go
- Bug fix
The --uuid flag for the `init`, `check-alerts`, `index` commands displayed a randomly-generated UUID as its default value in the help text. This was misleading to users, suggesting the value was hardcoded or that they needed to override a specific default.
This commit addresses the issue in two ways:
1.  The default value for the flag definition is changed to an empty string. This provides a clean and predictable --help output.
2.  Logic is added to the beginning of each command's execution to generate a new UUID if one was not provided by the user.
This approach results in a more intuitive user experience while ensuring that a unique benchmark UUID is always present at runtime, preserving the original functionality.
Old behavior:-
~~~
$kube-burner init --help
Launch benchmark …
> Fix(cli): Clarify default UUID behavior with help

- .github/workflows/docs.yml
- mkdocs.yml
- CI
the deploy-docs workflow was failing when trying to delete old documentation versions due to a grep pattern matching issue. the script used substring matching (`grep -q "$tag"`) which would incorrectly match partial version strings - for example, checking for "v1.2" would match "v1.20.6" and assume the documentation existed
this caused the workflow to attempt deleting non-existent versions like "v1.2" when only "v1.20.6" actually existed, resulting in: "error: unable to delete nonexistant identifier 'v1.2'"
the fix changes the grep pattern to use exact line matching (`grep -q "^$tag$"`) and updates mkdocs.yml to use the new material emoji extensions instead of the deprecated materialx.emoji extensions
also added error handling to prevent individual delete failures from breaking the …
> fix(ci): fix deploy-docs CI job failing on mike delete with substring matching

- docs/reference/configuration.md
- pkg/burner/kubevirt.go
- pkg/burner/object.go
- pkg/burner/waiters.go
- pkg/config/types.go
- Refactor
- New feature
- Bug fix
- Optimization
The state of the Ready condition is not guarantied to change during migration. Instead monitor the migrationState of the VMI
Support waiting on a gvr different from the original object gvr 
Add apiVersion to wait object
> Kubevirt ops migrate - wait on migrationState of VMI

- pkg/burner/waiters.go
- test/test-k8s.bats
- Bug fix
- CI
When waiting for resources to reach the desired state, list calls did not limit the list to the resources created by the current execution causing wait to hang on unrelated resources.
Add the current runid to the label selector when listing resources for wait
- Related Issue https://github.com/kube-burner/kube-burner-ocp/issues/263
> Waiters - limit resource list to ones created by the current run

- Makefile
- README.md
- Optimization
following up on #880 I found a way to add the missing security hardening features elegantly:
**1. FULL RELRO (relocation read-only)**
**2. position independent executable (PIE)**
**3. binary stripping**
**4. reproducible builds**
- updated `.goreleaser.yml` to split builds into linux (with full hardening) and other platforms
- added `build-hardened` target to Makefile for local hardened builds
- maintained backward compatibility with existing `build` and `build-release` targets
- security flags only applied to Linux builds as other platforms have different requirements
Component: build
- Closes #851
> feat(build): add missing security hardening flags for binary releases

- docs/measurements/index.md
- pkg/burner/kubevirt.go
- pkg/measurements/factory.go
- pkg/measurements/vmim_latency.go
- New feature
- Optimization
Allow monitoring live migration via the Virtual Machine Instance Migration resource
Replace the call to KubeVirt Migrate with creating the resource to allow controlling its labels
> Add support for VirtualMachineInstanceMigration latency

- pkg/measurements/base_measurement.go
- pkg/measurements/datavolume_latency.go
- pkg/measurements/job_latency.go
- pkg/measurements/netpol_latency.go
- pkg/measurements/node_latency.go
- pkg/measurements/pod_latency.go
- pkg/measurements/pvc_latency.go
- pkg/measurements/service_latency.go
- pkg/measurements/snapshot_latency.go
- pkg/measurements/vmi_latency.go
- pkg/measurements/vmim_latency.go
RouteAdvertisement latency measurement code in kube-burner-ocp is impacted by the kube-burner measurements refactoring PR #278 Exported some variables to fix this regression.
> Fix measurements regression

- pkg/util/fileutils/file_reader.go
- Bug fix
This logic was mistakenly deleted in #868, it works great now, as it allows to combine local and embedded configuration files in the same run, including alerts and metrics files too.
- Closes #
> Add back logic to detect config file in CWD

- pkg/measurements/pprof.go
- Added `-f` flag to curl commands to avoid writing HTTP error responses (like 404) to .pprof files.
- Ensures pprof collection fails fast per pod while keeping remaining pods unaffected.
- Prevents invalid profiles from being saved and logged.
> fail on HTTP errors when collecting pprofs

- .github/workflows/check-docs-links.yml
- CI
Lock lycheeVersion to v0.20.1
Remove --exclude-mail from check-docs-links as it is no longer supported
> GH Workflow check-docs - --exclude-mail flag was removed

- docs/reference/configuration.md
- pkg/config/config.go
- test/k8s/kube-burner-virt.yml
- test/k8s/kube-burner.yml
- Optimization
Increasing the number of default replicas and jobIterations to 1 helps to reduce complexity in configuration files, as these parameters won't be mandatory anymore.
> Bump default jobIterations and object replicas to 1
